#!/usr/bin/env python3
"""Hand translations part 1: prose (perks, archive manuals, pipboy, messages, keys, gui, jokes)."""

PROSE = {
# ===== advancement =====
"advancement.nukacraft.startup": "战争，从未改变……",
"advancement.nukacraft.startup_descript": "欢迎来到废土，孤独的旅人",

# ===== archive: Pip-Boy 手册 =====
"archive.nukacraft.main": "亲爱的庇护所居民！",
"archive.nukacraft.main_title": "你的哔哔小子",
"archive.nukacraft.discript": "亲爱的居民，它来了——哔哔小子！这是你的个人电脑，你在避难所生存离不开它。它记录并储存重要信息，还能读取全息磁带、与其他避难所科技设备互动。",
"archive.nukacraft.color_display": "显示颜色",
"archive.nukacraft.pipboy_color": "通过使用彩色全息磁带录制，你可以更换哔哔小子的配色。",
"archive.nukacraft.pipboy_holotape": "全息磁带及其用途",
"archive.nukacraft.useholotape": "要使用任何类型的全息磁带，你必须先在左手装备哔哔小子，然后右手握住全息影像并使用它。",
"archive.nukacraft.special_manual": "避难所科技 S.P.E.C.I.A.L. 手册",
"archive.nukacraft.special_ces": "避难所科技 C.E.S. 手册",
"archive.nukacraft.special_perks": "避难所科技辅助能力系统",
"archive.nukacraft.special_intro_title": "欢迎来到 S.P.E.C.I.A.L.！",
"archive.nukacraft.special_intro_desc": "恭喜！避难所科技选中了你来重建文明。但你不能两眼一抹黑地闯进废土。S.P.E.C.I.A.L. 系统就是你的生存蓝图。当你第一次走出避难所时，背包里会有一本赠送的「你很SPECIAL！」手册。翻开它，把你的基因档案录入哔哔小子，然后打开哔哔小子的属性（STAT）菜单开始分配初始点数。今天就规划你的未来吧，因为更好的未来在地下！",
"archive.nukacraft.special_attr_title": "核心属性",
"archive.nukacraft.special_attr_desc": "七大属性各自主导你生存的一个身体或精神面向。随着你投入点数（1 到 100+），你的基础数值会动态提升：\n\n力量提升你的近战伤害。\n感知提升你的远程伤害。\n耐力提升你的最大生命值和击退抗性。\n魅力改善商人价格并强化你的同伴。\n智力提升你的经验获取。\n敏捷决定你的移动和攻击速度。\n运气被动提升你找到额外战利品的几率。",
"archive.nukacraft.special_level_title": "升级与你",
"archive.nukacraft.special_level_desc": "活到老学到老，哪怕核弹已经落下！随着你击败敌人或开采资源获得经验，你会升级。每达到一个新的里程碑等级，哔哔小子就会慷慨地赠予你 1 点未分配的 S.P.E.C.I.A.L. 点数。\n\n警告：避难所科技提醒你，把辛苦赚来的经验浪费在神秘的「附魔台」上，将暂时取消你获取新 S.P.E.C.I.A.L. 点数的资格，直到你超过之前的最高等级。魔法不能替代科学！",
"archive.nukacraft.special_respec_title": "重置与增益",
"archive.nukacraft.special_respec_desc": "加错点了？别慌！如果你找到一本「你很不SPECIAL！」手册，阅读它会完全重置你的基因档案，返还所有点数，让你通过哔哔小子重新分配。\n\n你还能在世界各处找到绝密的避难所科技「技能书」，永久提升对应属性 1 点！最后，把烹饪技艺修炼到家的话，煮一锅「S.P.E.C.I.A.L.浓汤」可以获得暂时的全属性 +5 巨幅增益！",
"archive.nukacraft.special_scale_title": "废土动态难度",
"archive.nukacraft.special_scale_desc": "以为只有你在变强？再想想！废土会适应你的基因优势。敌对怪物会依据附近最高等级玩家的水平，被动调整自己的生命值、伤害和护甲。一个 50 级玩家引出的死亡爪，会比 5 级玩家的凶悍得多。永远带上一把更大的枪！",
"archive.nukacraft.ces_intro_title": "C.E.S. 介绍",
"archive.nukacraft.ces_intro_desc": "欢迎了解战斗效能评分（C.E.S.）！这套避难所科技专有算法会默默监视你清醒的每一刻来评估你的杀伤力。把它想象成一场标准化考试，只不过不及格的奖品是一座无名坟冢！",
"archive.nukacraft.ces_arch_title": "你是哪种类型？",
"archive.nukacraft.ces_arch_desc": "为了优化你最终的解剖流程，C.E.S. 子系统会将你归类为可识别的原型。无论你是「重装堡垒」、「玻璃大炮」，还是「消耗性肉块」，我们都为你准备了一个标着你名字的整齐文件夹！",
"archive.nukacraft.ces_calc_title": "谋杀的数学",
"archive.nukacraft.ces_calc_desc": "你的哔哔小子会激进地评判你的武器配置、装甲板、S.P.E.C.I.A.L. 属性和已激活的辅助能力，动态计算出你的 C.E.S.。高分？你就是一台行走的战争罪行！低分？你就是当地野生动物嘴里的一块放射性点心。",
"archive.nukacraft.ces_def_title": "红区警报",
"archive.nukacraft.ces_def_desc": "如果你的 C.E.S. 闪红，避难所科技强烈建议你狼狈地逃跑。在「红区」状态下与敌对目标交战，将违反你的避难所科技人寿保险条款（自然，保险随之作废）。",
"archive.nukacraft.ces_mp_title": "团队协同",
"archive.nukacraft.ces_mp_desc": "组队出行时，你的 C.E.S. 会向全队实时广播。这一关键数据能帮助队友在死亡爪来袭时，立刻认出谁跑得最慢。团队合作成就梦想！",
"archive.nukacraft.perks_intro_title": "沿着阶梯向上爬",
"archive.nukacraft.perks_intro_desc": "「平庸」是给赤色分子准备的！随着你升级并提升 S.P.E.C.I.A.L. 属性，哔哔小子会授权你解锁专属的「辅助能力」。这些专有的基因强化保证你死得比邻居们更有排面！",
"archive.nukacraft.perks_str_title": "力量辅助能力",
"archive.nukacraft.perks_str_desc": "因为有时候子弹太贵，你就是想用铅管敲一个超级变种人。像「铁拳」和「大联盟」这样的辅助能力，保证你的谈判简短、生硬且极其致命。",
"archive.nukacraft.perks_per_title": "感知辅助能力",
"archive.nukacraft.perks_per_desc": "能在一英里外把掠夺者蒸发，何必弄脏自己的手？用「狙击手」和「集中火力」磨砺你的专注。敏锐的眼睛意味着更干净的连体服！",
"archive.nukacraft.perks_end_title": "耐力辅助能力",
"archive.nukacraft.perks_end_desc": "献给那些把迎面枪林弹雨当成小麻烦的人！用「坚韧」和「生命赐予」强健体魄，让你这身血肉之躯面对等离子灼烧时，稍微没那么可悲。",
"archive.nukacraft.perks_cha_title": "魅力辅助能力",
"archive.nukacraft.perks_cha_desc": "有迷人的微笑和毫无道德底线的原则，谁还要枪？用你三寸不烂之舌配合「瓶盖收集者」敲诈商人，或者命令当地野生动物替你干脏活！",
"archive.nukacraft.perks_int_title": "智力辅助能力",
"archive.nukacraft.perks_int_desc": "书呆子们联合起来！用「科学！」和「药剂师」证明你的智力优越性。知识就是力量，但一把会射出爆炸等离子体的拼凑激光步枪，显然是更大的力量。",
"archive.nukacraft.perks_agi_title": "敏捷辅助能力",
"archive.nukacraft.perks_agi_desc": "像风一样……一阵高辐射、重武装的风！「行动男孩」和「潜行」这类辅助能力保证你能把掠夺者营地洗劫一空，并在他们吃完克拉姆罐头之前消失得无影无踪。",
"archive.nukacraft.perks_luc_title": "运气辅助能力",
"archive.nukacraft.perks_luc_desc": "有时候逻辑靠边站，你只想要一个奇迹！「更佳暴击」和「血腥混乱」让概率法则为你弯腰。数学很无聊。爆炸才好玩！",

# ===== perk names（matched1 未覆盖的按此；官方对齐优先）=====
"perk.nukacraft.action_boy.name": "行动男孩",
"perk.nukacraft.adrenaline.name": "肾上腺素",
"perk.nukacraft.ammosmith.name": "弹药匠",
"perk.nukacraft.aquaboy.name": "两栖男孩",
"perk.nukacraft.armorer.name": "护甲匠",
"perk.nukacraft.attack_dog.name": "攻击犬",
"perk.nukacraft.basher.name": "猛击者",
"perk.nukacraft.better_criticals.name": "更佳暴击",
"perk.nukacraft.big_leagues.name": "大联盟",
"perk.nukacraft.blacksmith.name": "铁匠",
"perk.nukacraft.blocker.name": "格挡者",
"perk.nukacraft.bloody_mess.name": "血腥混乱",
"perk.nukacraft.cap_collector.name": "瓶盖收集者",
"perk.nukacraft.chem_resistant.name": "抗药体质",
"perk.nukacraft.chemist.name": "药剂师",
"perk.nukacraft.cola_nut.name": "可乐迷",
"perk.nukacraft.commando.name": "突击队员",
"perk.nukacraft.concentrated_fire.name": "集中火力",
"perk.nukacraft.demolition_expert.name": "爆破专家",
"perk.nukacraft.educated.name": "受过教育",
"perk.nukacraft.escape_artist.name": "逃脱大师",
"perk.nukacraft.evasive.name": "闪避",
"perk.nukacraft.finesse.name": "缜密",
"perk.nukacraft.fireproof.name": "防火体质",
"perk.nukacraft.fortune_finder.name": "寻财者",
"perk.nukacraft.ghoulish.name": "尸鬼化",
"perk.nukacraft.goat_legs.name": "山羊腿",
"perk.nukacraft.grim_reapers_sprint.name": "死神冲刺",
"perk.nukacraft.gun_fu.name": "枪斗术",
"perk.nukacraft.gun_nut.name": "枪械迷",
"perk.nukacraft.gunslinger.name": "神枪手",
"perk.nukacraft.heave_ho.name": "使劲抛！",
"perk.nukacraft.heavy_gunner.name": "重枪手",
"perk.nukacraft.idiot_savant.name": "白痴学者",
"perk.nukacraft.inspirational.name": "以身作则",
"perk.nukacraft.iron_fist.name": "铁拳",
"perk.nukacraft.ironclad.name": "铁甲",
"perk.nukacraft.jury_rigging.name": "应急改装",
"perk.nukacraft.lead_belly.name": "铅肚皮",
"perk.nukacraft.lifegiver.name": "生命赐予",
"perk.nukacraft.light_step.name": "步履轻盈",
"perk.nukacraft.lone_wanderer.name": "独行者",
"perk.nukacraft.magnetic_personality.name": "人格魅力",
"perk.nukacraft.marathoner.name": "马拉松选手",
"perk.nukacraft.medic.name": "医师",
"perk.nukacraft.moving_target.name": "移动靶",
"perk.nukacraft.mysterious_stranger.name": "神秘陌生人",
"perk.nukacraft.negotiator.name": "谈判专家",
"perk.nukacraft.nerd_rage.name": "书呆之怒！",
"perk.nukacraft.night_person.name": "夜行者",
"perk.nukacraft.ninja.name": "忍者",
"perk.nukacraft.nuclear_physicist.name": "核物理学家",
"perk.nukacraft.pain_train.name": "痛苦列车",
"perk.nukacraft.pharma_farma.name": "药剂丰收",
"perk.nukacraft.philanthropist.name": "慈善家",
"perk.nukacraft.pickpocket.name": "扒手",
"perk.nukacraft.rad_resistance.name": "辐射抗性",
"perk.nukacraft.rad_sponge.name": "辐射海绵",
"perk.nukacraft.radicool.name": "辐射酷",
"perk.nukacraft.refractor.name": "折射体",
"perk.nukacraft.ricochet.name": "回旋弹",
"perk.nukacraft.robotics_expert.name": "机器人专家",
"perk.nukacraft.rooted.name": "扎根",
"perk.nukacraft.science.name": "科学！",
"perk.nukacraft.scrapper.name": "拾荒者",
"perk.nukacraft.scrounger.name": "搜刮者",
"perk.nukacraft.serendipity.name": "时来运转",
"perk.nukacraft.sneak.name": "潜行",
"perk.nukacraft.sniper.name": "狙击手",
"perk.nukacraft.solar_powered.name": "太阳能",
"perk.nukacraft.swift_learner.name": "快速学习",
"perk.nukacraft.tenderizer.name": "嫩肉锤",
"perk.nukacraft.toughness.name": "坚韧",
"perk.nukacraft.wasteland_whisperer.name": "废土低语者",
"perk.nukacraft.white_knight.name": "白骑士",
"perk.nukacraft.wrecking_ball.name": "破坏球",

# ===== perk descriptions =====
"perk.nukacraft.action_boy.desc": "分秒必争！你的行动点数回复速度更快。",
"perk.nukacraft.adrenaline.desc": "每一次击杀都为下一次供能。每击杀一名敌人便获得可叠加的伤害加成，随时间衰减。",
"perk.nukacraft.ammosmith.desc": "有了这个辅助能力，同样的钱永远能买到更多家伙！制作弹药时产量提高 50%%。",
"perk.nukacraft.aquaboy.desc": "水是你的盟友。你不再因游泳受到辐射伤害，并且可以在水下呼吸。",
"perk.nukacraft.armorer.desc": "保护自己免受废土危险。你现在可以制作和升级护甲改装件。更高等级解锁进阶图纸。",
"perk.nukacraft.attack_dog.desc": "你忠实的犬类伙伴可以缠住敌人，让你有更大的几率命中射击。",
"perk.nukacraft.basher.desc": "贴身肉搏！枪托猛击造成更多伤害，并有几率致残对手。造成 1.5 倍伤害和额外击退。",
"perk.nukacraft.better_criticals.desc": "进阶训练带来更狠的暴击！你的暴击现在造成额外 50%% 伤害。让每一发子弹都物有所值。",
"perk.nukacraft.big_leagues.desc": "挥出全垒打！每级提升近战武器伤害。",
"perk.nukacraft.blacksmith.desc": "点燃熔炉！你现在可以制作和升级近战武器改装件。更高等级解锁进阶图纸。",
"perk.nukacraft.blocker.desc": "杀不死你的会让你更硬。每级减少来自近战攻击的伤害。",
"perk.nukacraft.bloody_mess.desc": "你现在每级对所有目标造成 +5%% 额外伤害！看你的敌人炸成一滩血泥。美极了。",
"perk.nukacraft.cap_collector.desc": "你已经学会了交易的艺术！每级让你在任何商贩处的买卖价格都更优。",
"perk.nukacraft.chem_resistant.desc": "常年泡在药物里让你产生了耐受性。你更不容易成瘾，负面药水效果的持续时间减半。",
"perk.nukacraft.chemist.desc": "任何废土医生都会告诉你：药物持久一点才更有效！你使用的药物和药水持续时间每级延长。",
"perk.nukacraft.cola_nut.desc": "就是爱那核子可乐的气泡！核子可乐产品现在恢复双倍的口渴值，并延长有益效果。",
"perk.nukacraft.commando.desc": "可控点射，效率至上。自动武器每级造成更多伤害。",
"perk.nukacraft.concentrated_fire.desc": "咬住目标不放！对同一目标的每次后续命中都造成递增伤害。弹丸伤害提升 15%%。",
"perk.nukacraft.demolition_expert.desc": "爆炸越大越好！你的爆炸物每级造成更多伤害。满级时，你投掷武器时可以看到弹道弧线。",
"perk.nukacraft.educated.desc": "你上课时没走神。在基础智力加成之上，你从所有来源额外获得 +50%% 经验。",
"perk.nukacraft.escape_artist.desc": "说不见就不见！进入潜行状态时，32 格范围内的所有敌人立即失去你的踪迹。",
"perk.nukacraft.evasive.desc": "闪转腾挪！你获得被动几率完全规避来袭伤害。闪避几率每级提升，最高 15%%。",
"perk.nukacraft.finesse.desc": "你的攻击尽显灵巧！每级提升基础暴击几率。",
"perk.nukacraft.fireproof.desc": "怕热就别进厨房——有了这个辅助能力，你可以放心待在里面。每级减少火焰伤害。",
"perk.nukacraft.fortune_finder.desc": "你对亮闪闪的东西特别敏锐！每级在容器中找到更多瓶盖。",
"perk.nukacraft.ghoulish.desc": "没错，你是有点尸鬼气质，但这有什么坏处？辐射现在会治疗你而不是伤害你。",
"perk.nukacraft.goat_legs.desc": "你长了山羊一样的腿！每级减少坠落伤害。",
"perk.nukacraft.grim_reapers_sprint.desc": "死神与你同在！任何击杀都有几率完全恢复你的行动点数。",
"perk.nukacraft.gun_fu.desc": "你学会了把武术训练运用到枪战中！如果你完成击杀后 3 秒内再次攻击，将造成 +20%% 额外伤害。",
"perk.nukacraft.gun_nut.desc": "你对武器改装如痴如醉！解锁制作和升级枪械改装件的能力。2 级解锁进阶枪械配件。",
"perk.nukacraft.gunslinger.desc": "唤醒老西部之魂！你的非自动手枪每级造成更多伤害。",
"perk.nukacraft.heave_ho.desc": "用上你的腰马合力！你投掷的武器飞得更远、伤害更高。满级时速度最高乘以 1.6 倍。",
"perk.nukacraft.heavy_gunner.name": "重枪手",
"perk.nukacraft.heavy_gunner.desc": "多亏了练习和锻炼，重型枪械每级造成更多伤害。",
"perk.nukacraft.idiot_savant.desc": "你不笨！你只是……运气好！任何行动都有几率随机获得 3 倍或 5 倍经验。智力越低，触发越频繁。",
"perk.nukacraft.inspirational.desc": "因为你以身作则，你的同伴在战斗中造成更多伤害，并被动回复生命值。",
"perk.nukacraft.iron_fist.desc": "运气发劲，把对手砸进土里。每级提升徒手伤害。",
"perk.nukacraft.ironclad.desc": "你的皮肉天生坚如指甲。在不穿动力装甲时，获得额外伤害抗性和能量抗性。",
"perk.nukacraft.jury_rigging.desc": "你几乎能用任何东西修好任何东西！每级允许你用相似的垃圾物品修理物品。",
"perk.nukacraft.lead_belly.desc": "你的铁胃让你能吃辐照食物而少受辐射伤害。每级减少食物带来的辐射。",
"perk.nukacraft.lifegiver.desc": "你就是生存意志的化身！每级立刻获得额外最大生命值。更高级时，你会缓慢回复已损失生命。",
"perk.nukacraft.light_step.desc": "避难所科技的训练没有白费！你不会触发压力板或绊线。在废土中行走，无惧陷阱。",
"perk.nukacraft.lone_wanderer.desc": "谁还需要朋友？独自冒险时，你每级受到更少伤害并可携带更多物品。",
"perk.nukacraft.magnetic_personality.desc": "你的魅力极具感染力！你的同伴永久获得 +2 攻击伤害和 +10 最大生命值。",
"perk.nukacraft.marathoner.desc": "你为奔跑而生！疾跑每级消耗的行动点数大幅减少。满级时，疾跑不产生疲劳。",
"perk.nukacraft.medic.desc": "有医生在吗？治疗针和消辐宁每级更有效。",
"perk.nukacraft.moving_target.desc": "移动靶更难打中！疾跑时获得额外伤害抗性，且受击时按等级获得递增闪避几率。",
"perk.nukacraft.mysterious_stranger.desc": "他是谁？为什么帮你？管他呢！神秘陌生人会在战斗中偶尔现身助你一臂之力，效率致命。",
"perk.nukacraft.negotiator.desc": "你总能占得上风。每级降低买入价格并提高卖出价格。",
"perk.nukacraft.nerd_rage.desc": "愤怒是最好的麻醉剂！当你的生命值低于 25%% 时，时间减慢，你造成 +20%% 伤害。肾上腺素令人迷醉。",
"perk.nukacraft.night_person.desc": "你是黑夜的生物！在晚 6 点到早 6 点之间获得智力和感知加成。",
"perk.nukacraft.ninja.desc": "修习古老技艺！你的偷袭造成更多伤害，远程偷袭每级造成更高伤害。",
"perk.nukacraft.nuclear_physicist.desc": "你已精通原子！聚变核心持续更久，你的辐射武器每级造成更多伤害。",
"perk.nukacraft.pain_train.desc": "呜呜——全体上车！身穿动力装甲冲向敌人会造成伤害并击退他们。",
"perk.nukacraft.pharma_farma.desc": "你总能找到好东西！打开容器时，有 5%% 几率里面凭空出现一支治疗针。",
"perk.nukacraft.philanthropist.desc": "分享就是关怀！你进食或饮水时，处于激活状态的同伴也会回复 10 点生命值。",
"perk.nukacraft.pickpocket.desc": "你手快手黏，是偷窃商人的行家。解锁从废土商人身上扒窃的能力。",
"perk.nukacraft.rad_resistance.desc": "严酷废土的洗礼只会让你更皮实！你现在拥有更高的辐射抗性。减少 40%% 所受辐射。",
"perk.nukacraft.rad_sponge.desc": "你的身体像海绵吸水一样吸收辐射。你会随时间被动流失少量辐射值。",
"perk.nukacraft.radicool.desc": "辐射越高，你越强！根据当前辐射等级获得额外力量。每 200 辐射 +1 力量。",
"perk.nukacraft.refractor.desc": "你一定是半个镜子做的！每级立刻获得更高的能量抗性。",
"perk.nukacraft.ricochet.desc": "出来混总是要还的！当敌人用弹丸命中你时，有 10%% 几率将伤害反弹给攻击者。",
"perk.nukacraft.robotics_expert.desc": "机器屈从于你的意志。潜行并与机器人类型的敌人互动即可骇入并将其变成盟友。类似废土低语者，但目标是机械体。",
"perk.nukacraft.rooted.desc": "你是大地的一部分。站立不动时，你获得更高的伤害抗性，近战和远程武器造成更多伤害。",
"perk.nukacraft.science.desc": "充分利用先进科技。每级解锁武器和护甲的高科技改装件。",
"perk.nukacraft.scrapper.desc": "物尽其用！制作物品时，有 15%% 几率额外产出一份成品。",
"perk.nukacraft.scrounger.desc": "总会有更多弹药藏在某个角落。每级在废土各处的容器中找到更多弹药。",
"perk.nukacraft.serendipity.desc": "幸运女神罩着你！当生命值低于 30%% 时，来袭伤害有几率被完全抵消。冷却 5 分钟。",
"perk.nukacraft.sneak.desc": "变得悄无声息！潜行时更难被察觉。更高级时你几乎隐形。",
"perk.nukacraft.sniper.desc": "全凭专注。每级提升瞄准武器精度，并有几率击倒目标。",
"perk.nukacraft.solar_powered.desc": "沐浴阳光！在早 6 点到晚 6 点之间获得额外的力量和耐力。",
"perk.nukacraft.swift_learner.desc": "你从所有来源获得的经验每级增加。在废土，知识字面意义上就是力量。",
"perk.nukacraft.tenderizer.desc": "先把他们腌软！你近战命中的目标在短时间内受到更多伤害。施加虚弱 II，持续 3 秒。",
"perk.nukacraft.toughness.desc": "就算没别的本事，你挨打也像个冠军！每级立刻获得更高的伤害抗性。",
"perk.nukacraft.wasteland_whisperer.desc": "你对废土生物自有一套。将准星对准等级低于你的动物并尝试安抚它。蹲下并空手互动来驯服。基础成功率 30%%。",
"perk.nukacraft.white_knight.desc": "你的护甲经久耐用！护甲受击损耗几率降低 25%%。",
"perk.nukacraft.wrecking_ball.desc": "给我一根足够长的杠杆，我就能撬动世界！你的方块破坏速度提高 50%%。",

# ===== S.P.E.C.I.A.L. 面板 =====
"pipboy.nukacraft.special.agility.name": "敏捷",
"pipboy.nukacraft.special.charisma.name": "魅力",
"pipboy.nukacraft.special.endurance.name": "耐力",
"pipboy.nukacraft.special.intelligence.name": "智力",
"pipboy.nukacraft.special.luck.name": "运气",
"pipboy.nukacraft.special.perception.name": "感知",
"pipboy.nukacraft.special.strength.name": "力量",
"pipboy.nukacraft.special.agility.short": "敏捷",
"pipboy.nukacraft.special.charisma.short": "魅力",
"pipboy.nukacraft.special.endurance.short": "耐力",
"pipboy.nukacraft.special.intelligence.short": "智力",
"pipboy.nukacraft.special.luck.short": "运气",
"pipboy.nukacraft.special.perception.short": "感知",
"pipboy.nukacraft.special.strength.short": "力量",
"pipboy.nukacraft.special.agility.desc": "敏捷衡量你的整体灵巧度与反应速度。它影响你的行动点数池和潜行能力。",
"pipboy.nukacraft.special.agility.boost": "每点提升移动速度、加快近战攻击速度，并降低饥饿疲劳。",
"pipboy.nukacraft.special.charisma.desc": "魅力是你迷住并说服他人的能力。它影响对话说服的成功率、交易价格，以及同伴的强度。",
"pipboy.nukacraft.special.charisma.boost": "提升商人处的买卖价格，并改善同伴的战斗属性。",
"pipboy.nukacraft.special.endurance.desc": "耐力衡量你的整体体能。它影响你的总生命值，以及疾跑时行动点数的消耗速度。",
"pipboy.nukacraft.special.endurance.boost": "每点提升最大生命值 +2，并增加击退抗性。",
"pipboy.nukacraft.special.intelligence.desc": "智力衡量你的整体心智敏锐度。它影响获得的经验点数，并决定你能掌握多少张制作图纸。",
"pipboy.nukacraft.special.intelligence.boost": "每点提升经验获取 4%%。",
"pipboy.nukacraft.special.luck.desc": "运气衡量你的整体好运，影响暴击的充能速度。运气更高的幸存者会在容器中找到更好的物品，并有更高几率打出暴击。",
"pipboy.nukacraft.special.luck.boost": "每点提升拾取等级、原版幸运属性和枪械暴击几率。",
"pipboy.nukacraft.special.perception.desc": "感知是你的环境觉察力和第六感。它让敌人无法偷袭你，并直接提升你的远程武器伤害。",
"pipboy.nukacraft.special.perception.boost": "每点提升枪械伤害 4%%。更高的感知扩大罗盘侦测范围。",
"pipboy.nukacraft.special.strength.desc": "力量衡量你的原始体能。它影响你的携带量，并决定所有近战攻击的效能。",
"pipboy.nukacraft.special.strength.boost": "每点提升近战伤害 +0.75，并提高挖掘速度 4%%。",

# ===== messages =====
"message.nukacraft.ammosmith_required": "你需要「弹药匠」辅助能力才能制作弹药！",
"message.nukacraft.armorer_required": "你需要「护甲匠」辅助能力才能制作这个！",
"message.nukacraft.blacksmith_rank2_required": "你需要 2 级「铁匠」才能制作近战配件！",
"message.nukacraft.blacksmith_required": "你需要「铁匠」辅助能力才能制作这个！",
"message.nukacraft.gun_nut_rank2_required": "你需要 2 级「枪械迷」才能制作枪械配件！",
"message.nukacraft.gun_nut_required": "你需要「枪械迷」辅助能力才能制作这个！",
"message.nukacraft.mysterious_stranger_appeared": "一道黑影从黑暗中走出……",
"message.nukacraft.pickpocket_required": "你需要「扒手」辅助能力才能行窃！",
"message.nukacraft.robotics_cooldown": "「机器人专家」冷却中！还剩 %s 秒。",
"message.nukacraft.robotics_failed": "%s 抵抗了你的骇入尝试！",
"message.nukacraft.robotics_hacked": "%s 已被骇入！",
"message.nukacraft.science_rank2_required": "你需要 2 级「科学！」才能制作这个。",
"message.nukacraft.science_required": "你需要「科学！」辅助能力才能制作这个。",
"message.nukacraft.whisperer_cooldown": "「废土低语者」冷却中！还剩 %s 秒。",
"message.nukacraft.whisperer_failed": "%s 抵抗了你的尝试！",
"message.nukacraft.whisperer_fallen": "你安抚的 %s 倒下了！",
"message.nukacraft.whisperer_pacified": "%s 已被安抚！",

# ===== 按键 =====
"key.categories.nukacraft.ui": "NukaCraft 界面",
"key.nukacraft.armor_mask": "打开动力装甲头盔",
"key.nukacraft.container_store_all": "容器：全部存入",
"key.nukacraft.container_take_all": "容器：全部拿取",
"key.nukacraft.full_loot": "打开完整战利品",
"key.nukacraft.inspect_reset": "检视：复位",
"key.nukacraft.inspect_spin": "检视：旋转",
"key.nukacraft.merchant_confirm": "商人：确认交易",
"key.nukacraft.merchant_reset": "商人：重置交易",
"key.nukacraft.open_pipboy": "打开哔哔小子",
"key.nukacraft.open_pipboy_map": "打开哔哔小子（地图）",
"key.nukacraft.open_pipboy_radio": "打开哔哔小子（电台）",
"key.nukacraft.station_apply_mod": "工作台：应用改装",
"key.nukacraft.station_equip": "工作台：装备/卸下",
"key.nukacraft.station_mask": "工作台：切换面罩",
"key.nukacraft.station_modify": "工作台：改装模式",
"key.nukacraft.station_part_next": "工作台：下一部件",
"key.nukacraft.station_part_prev": "工作台：上一部件",
"key.nukacraft.station_remove_mod": "工作台：移除改装",
"key.nukacraft.ui_accept": "界面：确认/选择",
"key.nukacraft.ui_close": "界面：关闭/返回",
"key.nukacraft.ui_inspect": "界面：检视",
"key.nukacraft.ui_sort": "界面：整理",
"key.nukacraft.ui_theme": "界面：主题",
"key.open_map": "打开地图",

# ===== GUI =====
"gui.nukacraft.addMarker": "添加标记",
"gui.nukacraft.container.close_hint": "[Esc] 关闭",
"gui.nukacraft.container.slots_usage": "%1$s/%2$s",
"gui.nukacraft.container.sort_quantity": "数量",
"gui.nukacraft.container.store_all": "全部存入",
"gui.nukacraft.delMarker": "删除标记",
"gui.nukacraft.hideMarkers": "隐藏所有标记",
"gui.nukacraft.marker.tomb": "%s 长眠于此",
"gui.nukacraft.quick_loot.hint": "[E] 拿取　[R] 全拿　[Tab] 完整　[Esc] 关闭",
"gui.nukacraft.quick_loot.transfer": "转移 ▸",
"gui.nukacraft.scalebar": "地图比例",
"gui.nukacraft.showMarkers": "显示所有标记",
"gui.nukacraft.station.back": "[TAB] 返回",
"gui.nukacraft.station.current_mods": "当前改装：",
"gui.nukacraft.station.equip": "[E] 装备",
"gui.nukacraft.station.inspect": "[Z] 检视",
"gui.nukacraft.station.resistance": "抗性",
"gui.nukacraft.station.theme": "[V] 主题",
"gui.nukacraft.station.unequip": "[X] 卸下",
"gui.nukacraft.workbench.tab.attachments": "配件",
"gui.nukacraft.workbench.tab.melee": "近战武器",
"hud.nukacraft.lv": "等级",
"nukacraft:scrap_box_scrap_mode_toggle": "切换拆解模式",
"slot.nukacraft.attachment.shield": "盾牌",

# ===== 死亡信息 =====
"death.attack.bullet": "%1$s被%2$s射杀了",
"death.attack.bullet.item": "%1$s被%2$s用%3$s射杀了",
"death.attack.nukacraft.death.eliminated": "%1$s对{ULTRA}有了更深入的了解",
"death.attack.nukacraft.death.killed": "%1$s溶解成了{ULTRA}",

# ===== 茶与提示 =====
"tooltip.nukacraft.details": "§7按住 Shift 查看详情",
"tooltip.nukacraft.haste": "§9急迫 ",
"tooltip.nukacraft.jumpboost": "§9跳跃提升 ",
"tooltip.nukacraft.regen": "§9再生 ",
"tooltip.nukacraft.icy": "§e冰爽",
"tooltip.nukacraft.tea_thistle": "§7味道不怎么样，但能压压饥饿",
"use.nukacraft.acid": "§7右键点击你想使其生锈的物品",
"use.nukacraft.cleaner": "§7右键点击你想清洁的物品",
"use.nukacraft.repairkit": "§7右键点击需要部分修理的物品",
"use.nukacraft.repairkit2": "§7右键+Ctrl 点击需要整套修理包来修理的物品",

# ===== 包装纸笑话 =====
"text.nukacraft.blank": "包装纸上的字：",
"text.nukacraft.funnies_0": "§7克拉姆罐头走进酒吧。\n酒保说：「本店不招待食品！」",
"text.nukacraft.funnies_1": "§7一个巧手先生走进酒吧。\n「哎哟！」它喊道。",
"text.nukacraft.funnies_2": "§7战后最好的披萨？\n加量芝士，蘑菇云免了。",
"text.nukacraft.funnies_3": "§7我有一本全世界最烂的同义词词典。\n它糟糕透顶、糟糕透顶。",
"text.nukacraft.funnies_4": "§7警察要看我的执照。\n我告诉他我还没结婚。",
"text.nukacraft.funnies_5": "§7拼些银是门适传的移术。",
"text.nukacraft.funnies_6": "§7墨西哥卷饼导完电影说：\n「杀青了，包好了！」",
"text.nukacraft.funnies_7": "§7盲人时装设计师最喜欢的颜色是什么？\n灯芯绒。",
"text.nukacraft.funnies_8": "§7听说那个失踪的法老了吗？\n他就是想要他的妈咪。",

# ===== 哔哔小子杂项 =====
"pipboy.nukacraft.clicks": "§7打开哔哔小子：查看按键设置",
"pipboy.nukacraft.data": "▪档案",
"pipboy.nukacraft.handselect": "§7左手持有时：",
"pipboy.nukacraft.map": "▪地图",
"pipboy.nukacraft.rad": "辐射",
"pipboy.nukacraft.radio": "▪电台",
"pipboy.nukacraft.radio.appalachia": "阿巴拉契亚电台",
"pipboy.nukacraft.radio.classical": "古典电台",
"pipboy.nukacraft.screencolor": "§7界面颜色：",

# ===== 哔哔小子 UI =====
"pipboy.nukacraft.ui.access_granted": ">> 访问许可 <<",
"pipboy.nukacraft.ui.allocation_cancelled": "已取消",
"pipboy.nukacraft.ui.allocation_success": "属性点已分配！",
"pipboy.nukacraft.ui.applied": "已应用",
"pipboy.nukacraft.ui.apply_prompt": "[回车] 应用　|　[Esc] 取消",
"pipboy.nukacraft.ui.apply_screen": "应用屏幕颜色：%s？",
"pipboy.nukacraft.ui.apply_shell": "应用外壳颜色：%s？",
"pipboy.nukacraft.ui.attack_speed": "攻击速度",
"pipboy.nukacraft.ui.awaiting_confirmation": "[回车] 应用　|　[Esc] 取消",
"pipboy.nukacraft.ui.bonus_looting": "拾取加成",
"pipboy.nukacraft.ui.buy_discount": "购买折扣",
"pipboy.nukacraft.ui.ces": "C.E.S.",
"pipboy.nukacraft.ui.color_label": "颜色：%s",
"pipboy.nukacraft.ui.color_mod": "颜色改装 [%s]",
"pipboy.nukacraft.ui.color_mod_utility": "颜色改装工具",
"pipboy.nukacraft.ui.companion_dmg": "同伴伤害",
"pipboy.nukacraft.ui.companion_hp": "同伴生命值",
"pipboy.nukacraft.ui.confirm": "确认",
"pipboy.nukacraft.ui.confirm_allocation": "将属性点分配给 %s？",
"pipboy.nukacraft.ui.confirm_unlock": "解锁辅助能力",
"pipboy.nukacraft.ui.confirm_upgrade": "升级辅助能力",
"pipboy.nukacraft.ui.crit_chance": "暴击几率",
"pipboy.nukacraft.ui.crit_dmg_mult": "暴击伤害倍率",
"pipboy.nukacraft.ui.current_settlement": "当前定居点：",
"pipboy.nukacraft.ui.deaths": "死亡次数",
"pipboy.nukacraft.ui.dmg_dealt": "造成伤害",
"pipboy.nukacraft.ui.dmg_taken": "受到伤害",
"pipboy.nukacraft.ui.door_closing": "大门正在关闭",
"pipboy.nukacraft.ui.door_control": "避难所科技门控系统",
"pipboy.nukacraft.ui.door_control_system": "避难所科技门控系统",
"pipboy.nukacraft.ui.door_opening": "大门正在开启",
"pipboy.nukacraft.ui.door_version": "v3.7.1   机密",
"pipboy.nukacraft.ui.effects": "效果",
"pipboy.nukacraft.ui.establishing_uplink": "正在建立上行链路",
"pipboy.nukacraft.ui.exhaustion_red": "疲劳降低",
"pipboy.nukacraft.ui.fallout76": "辐射76",
"pipboy.nukacraft.ui.fly_m": "飞行距离（米）",
"pipboy.nukacraft.ui.happiness": "幸福度",
"pipboy.nukacraft.ui.holotape_detected": "检测到全息磁带",
"pipboy.nukacraft.ui.holotape_reader": "全息磁带读取器",
"pipboy.nukacraft.ui.initializing": "初始化中",
"pipboy.nukacraft.ui.jumps": "跳跃次数",
"pipboy.nukacraft.ui.knockback_res": "击退抗性",
"pipboy.nukacraft.ui.level": "等级",
"pipboy.nukacraft.ui.loading": "加载中",
"pipboy.nukacraft.ui.loading_holotape": "正在加载全息磁带",
"pipboy.nukacraft.ui.local_scan": "局部扫描",
"pipboy.nukacraft.ui.marker_name": "标记名称",
"pipboy.nukacraft.ui.max_hp": "最大生命值",
"pipboy.nukacraft.ui.max_rank": "已达最高等级",
"pipboy.nukacraft.ui.melee_dmg": "近战伤害",
"pipboy.nukacraft.ui.mining_spd": "挖掘速度",
"pipboy.nukacraft.ui.mob_kills": "生物击杀数",
"pipboy.nukacraft.ui.modification_complete": "改装完成",
"pipboy.nukacraft.ui.no": "[Esc] 否",
"pipboy.nukacraft.ui.no_archives": "未找到档案",
"pipboy.nukacraft.ui.no_changes": "未检测到更改",
"pipboy.nukacraft.ui.no_changes_made": "未做任何更改",
"pipboy.nukacraft.ui.no_points": "没有可用的辅助能力点数",
"pipboy.nukacraft.ui.no_quest_data": "没有可用的任务数据",
"pipboy.nukacraft.ui.no_signal": "无信号",
"pipboy.nukacraft.ui.operation_cancelled": "操作已取消",
"pipboy.nukacraft.ui.pending_application": "待应用",
"pipboy.nukacraft.ui.pipboy_shell_unit": "哔哔小子外壳单元",
"pipboy.nukacraft.ui.player_kills": "玩家击杀数",
"pipboy.nukacraft.ui.please_wait": "请稍候",
"pipboy.nukacraft.ui.points_available": "可用点数：",
"pipboy.nukacraft.ui.press_any_key": "[按任意键退出]",
"pipboy.nukacraft.ui.ranged_dmg": "远程伤害",
"pipboy.nukacraft.ui.rank": "等级：",
"pipboy.nukacraft.ui.reading_media": "正在读取媒体",
"pipboy.nukacraft.ui.requirements_unmet": "未满足需求",
"pipboy.nukacraft.ui.robco_copyright": "版权所有 2075-2077 罗伯科工业",
"pipboy.nukacraft.ui.robco_server": "6号服务器 - 避难所科技",
"pipboy.nukacraft.ui.robco_title": "罗伯科工业（TM）终端链路",
"pipboy.nukacraft.ui.scanning_vault_door": "正在扫描避难所大门",
"pipboy.nukacraft.ui.screen_color": "屏幕颜色：",
"pipboy.nukacraft.ui.screen_color_applied": "屏幕颜色已应用",
"pipboy.nukacraft.ui.searching_area": "正在搜索区域",
"pipboy.nukacraft.ui.sectors_scanned": "已扫描扇区：%s/48",
"pipboy.nukacraft.ui.select_a": "选择一个",
"pipboy.nukacraft.ui.select_archive": "选择一个档案",
"pipboy.nukacraft.ui.select_item": "选择物品",
"pipboy.nukacraft.ui.select_perk": "选择一个辅助能力查看",
"pipboy.nukacraft.ui.select_quest": "选择一个任务",
"pipboy.nukacraft.ui.sell_bonus": "出售加成",
"pipboy.nukacraft.ui.shell_color": "外壳颜色：",
"pipboy.nukacraft.ui.shell_color_applied": "外壳颜色已应用",
"pipboy.nukacraft.ui.shell_screen_color": "外壳+屏幕：%s",
"pipboy.nukacraft.ui.skipped": "已跳过",
"pipboy.nukacraft.ui.sleep_in_bed": "睡眠次数",
"pipboy.nukacraft.ui.special_stat": "S.P.E.C.I.A.L. 属性",
"pipboy.nukacraft.ui.sprint_m": "疾跑距离（米）",
"pipboy.nukacraft.ui.swim_m": "游泳距离（米）",
"pipboy.nukacraft.ui.terminal_link_active": "终端链路已激活",
"pipboy.nukacraft.ui.transmit_close": "正在传输关闭指令",
"pipboy.nukacraft.ui.transmit_open": "正在传输开启指令",
"pipboy.nukacraft.ui.tuning": "调谐中……",
"pipboy.nukacraft.ui.unlocked_perks": "已解锁辅助能力",
"pipboy.nukacraft.ui.vault_door_located": "已定位避难所大门",
"pipboy.nukacraft.ui.version": "v1.0.3-VT",
"pipboy.nukacraft.ui.walk_m": "步行距离（米）",
"pipboy.nukacraft.ui.wg": "WG",
"pipboy.nukacraft.ui.world_map": "世界地图",
"pipboy.nukacraft.ui.yes": "[回车] 是",
"pipboy.nukacraft.ui.hunger": "行动点数",
"pipboy.nukacraft.ui.caps": "瓶盖",

# ===== 皮肤/染色 =====
"skin.cyan": "§b§o青色颜料",
"skin.green": "§b§o绿色颜料",
"skin.light_gray": "§b§o淡灰色颜料",
"skin.lime": "§b§o黄绿色颜料",
"skin.magenta": "§b§o品红色颜料",
"skin.purple": "§b§o紫色颜料",

# ===== 物品栏标签页 =====
"itemGroup.nuka_armor": "NukaCraft：护甲",
"itemGroup.nuka_blocks": "NukaCraft：建筑方块",
"itemGroup.nuka_equip": "NukaCraft：武器",
"itemGroup.nuka_foods": "NukaCraft：食物",
"itemGroup.nuka_material": "NukaCraft：杂物",
"itemGroup.nuka_mobs": "NukaCraft：生物",
"itemGroup.nuka_plants": "NukaCraft：植物",
"itemGroup.power_armor": "NukaCraft：动力装甲",

# ===== 容器 =====
"container.fridge": "现代冰箱",
"container.nukacraft.storage": "储物箱",

# ===== 油画 =====
"painting.nukacraft.nukacola.title": "核子可乐海报",
"painting.nukacraft.quantcola.title": "量子核子可乐海报",
"painting.nukacraft.painting_bos.title": "钢铁兄弟会旗帜",
"painting.nukacraft.painting_enc.title": "英克雷旗帜",
"painting.nukacraft.painting_enc2.title": "英克雷旗帜",
"painting.nukacraft.painting_legion.title": "凯撒军团旗帜",
"painting.nukacraft.painting_mntm.title": "义勇军旗帜",
"painting.nukacraft.painting_ncr.title": "NCR 旗帜",
"painting.nukacraft.screen_paint.title": "终端屏幕",
"painting.nukacraft.screen_paint2.title": "终端屏幕",
"painting.nukacraft.screen_rhouse.title": "罗伯特·豪斯屏幕",
"painting.nukacraft.screen_rhouse2.title": "罗伯特·豪斯屏幕",
"painting.nukacraft.sugar_bomb_promo.title": "糖弹海报",
"painting.nukacraft.vault_promo.title": "避难所科技海报",
"painting.nukacraft.vault_promo2.title": "避难所科技海报",
"painting.nukacraft.vault_promo3.title": "避难所科技海报",
"painting.nukacraft.vault_promo4.title": "避难所科技海报",
}
