#!/usr/bin/env python3
"""Hand translations part 2: items, blocks, entities, biomes, misc — following
official F76 zhhans conventions confirmed by probing."""

NAMES = {
# ===== biomes =====
"biome.nukacraft.alien_region": "外星区域",
"biome.nukacraft.ash_forest": "灰烬森林",
"biome.nukacraft.cold_glow_sea": "寒冷发光海",
"biome.nukacraft.deep_cold_glow_sea": "深层寒冷发光海",
"biome.nukacraft.flooded_dunes": "淹水沙丘",
"biome.nukacraft.frosted_creek": "霜冻溪流",
"biome.nukacraft.frozen_dunes": "冰冻沙丘",
"biome.nukacraft.glow_ice": "发光冰原",
"biome.nukacraft.glow_sea_abyss": "发光海深渊",
"biome.nukacraft.lichen_caves": "地衣洞穴",
"biome.nukacraft.mojave": "莫哈维",
"biome.nukacraft.permafrost": "永冻土",
"biome.nukacraft.permafrost_forest": "永冻森林",
"biome.nukacraft.rust_plains": "锈蚀平原",
"biome.nukacraft.rusted_creek": "锈蚀溪流",
"biome.nukacraft.savage_divide_plateau": "险恶划分高原",
"biome.nukacraft.scorched_lands": "焦土之地",
"biome.nukacraft.scorched_plains": "焦土平原",
"biome.nukacraft.snow_savage_divide": "雪境险恶划分",
"biome.nukacraft.sunlight_forest": "阳光森林",
"biome.nukacraft.sunlight_meadows": "阳光草甸",
"biome.nukacraft.ultracite_caves": "辐射极琉矿洞穴",
"biome.nukacraft.windswept_rust_plains": "风吹锈蚀平原",
"biome.nukacraft.windswept_savage_divide": "风吹险恶划分",
"biome.nukacraft.windswept_sunlight_meadows": "风吹阳光草甸",

# ===== entities =====
"entity.nukacraft.ant": "巨型蚂蚁",
"entity.nukacraft.bighorner": "大角羊",
"entity.nukacraft.cazador": "尾刺螫蝇",
"entity.nukacraft.companion": "同伴",
"entity.nukacraft.frank_horrigan": "弗兰克·霍里根",
"entity.nukacraft.human_merchant": "废土商人",
"entity.nukacraft.iguana": "鬣蜥",
"entity.nukacraft.mantis": "巨型螳螂",
"entity.nukacraft.securitron": "安保机器人",
"entity.nukacraft.wasteland_merchant": "废土商人",

# ===== banner colors =====
"block.minecraft.banner.nukacraft.bos.black": "黑色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.blue": "蓝色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.brown": "棕色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.cyan": "青色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.gray": "灰色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.green": "绿色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.light_blue": "淡蓝色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.light_gray": "淡灰色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.lime": "黄绿色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.magenta": "品红色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.orange": "橙色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.pink": "粉红色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.purple": "紫色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.red": "红色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.white": "白色钢铁兄弟会",
"block.minecraft.banner.nukacraft.bos.yellow": "黄色钢铁兄弟会",

# ===== steel color family (official: 白钢/黑钢 style) =====
"block.nukacraft.black_steel": "黑钢",
"block.nukacraft.black_steel2": "标记黑钢",
"block.nukacraft.marked_black_steel": "标记黑钢",
"block.nukacraft.black_steel_corrugated_plate": "黑钢瓦楞板",
"block.nukacraft.black_steel_slab": "黑钢台阶",
"block.nukacraft.black_steel_stairs": "黑钢楼梯",
"block.nukacraft.blue_steel": "蓝钢",
"block.nukacraft.blue_steel_corrugated_plate": "蓝钢瓦楞板",
"block.nukacraft.blue_steel_slab": "蓝钢台阶",
"block.nukacraft.blue_steel_stairs": "蓝钢楼梯",
"block.nukacraft.brown_steel": "棕钢",
"block.nukacraft.brown_steel_corrugated_plate": "棕钢瓦楞板",
"block.nukacraft.brown_steel_slab": "棕钢台阶",
"block.nukacraft.brown_steel_stairs": "棕钢楼梯",
"block.nukacraft.cyan_steel": "青钢",
"block.nukacraft.cyan_steel_corrugated_plate": "青钢瓦楞板",
"block.nukacraft.cyan_steel_slab": "青钢台阶",
"block.nukacraft.cyan_steel_stairs": "青钢楼梯",
"block.nukacraft.gray_steel": "灰钢",
"block.nukacraft.gray_steel_corrugated_plate": "灰钢瓦楞板",
"block.nukacraft.gray_steel_slab": "灰钢台阶",
"block.nukacraft.gray_steel_stairs": "灰钢楼梯",
"block.nukacraft.green_steel": "绿钢",
"block.nukacraft.green_steel_corrugated_plate": "绿钢瓦楞板",
"block.nukacraft.green_steel_slab": "绿钢台阶",
"block.nukacraft.green_steel_stairs": "绿钢楼梯",
"block.nukacraft.light_blue_steel": "淡蓝钢",
"block.nukacraft.light_blue_steel_corrugated_plate": "淡蓝钢瓦楞板",
"block.nukacraft.light_blue_steel_slab": "淡蓝钢台阶",
"block.nukacraft.light_blue_steel_stairs": "淡蓝钢楼梯",
"block.nukacraft.light_gray_steel": "淡灰钢",
"block.nukacraft.light_gray_steel_corrugated_plate": "淡灰钢瓦楞板",
"block.nukacraft.light_gray_steel_slab": "淡灰钢台阶",
"block.nukacraft.light_gray_steel_stairs": "淡灰钢楼梯",
"block.nukacraft.lime_steel": "黄绿钢",
"block.nukacraft.lime_steel_corrugated_plate": "黄绿钢瓦楞板",
"block.nukacraft.lime_steel_slab": "黄绿钢台阶",
"block.nukacraft.lime_steel_stairs": "黄绿钢楼梯",
"block.nukacraft.magenta_steel": "品红钢",
"block.nukacraft.magenta_steel_corrugated_plate": "品红钢瓦楞板",
"block.nukacraft.magenta_steel_slab": "品红钢台阶",
"block.nukacraft.magenta_steel_stairs": "品红钢楼梯",
"block.nukacraft.orange_steel": "橙钢",
"block.nukacraft.orange_steel_corrugated_plate": "橙钢瓦楞板",
"block.nukacraft.orange_steel_slab": "橙钢台阶",
"block.nukacraft.orange_steel_stairs": "橙钢楼梯",
"block.nukacraft.pink_steel": "粉钢",
"block.nukacraft.pink_steel_corrugated_plate": "粉钢瓦楞板",
"block.nukacraft.pink_steel_slab": "粉钢台阶",
"block.nukacraft.pink_steel_stairs": "粉钢楼梯",
"block.nukacraft.platedgreen_steel": "镀层绿钢",
"block.nukacraft.purple_steel": "紫钢",
"block.nukacraft.purple_steel_corrugated_plate": "紫钢瓦楞板",
"block.nukacraft.purple_steel_slab": "紫钢台阶",
"block.nukacraft.purple_steel_stairs": "紫钢楼梯",
"block.nukacraft.red_steel": "红钢",
"block.nukacraft.red_steel_corrugated_plate": "红钢瓦楞板",
"block.nukacraft.red_steel_slab": "红钢台阶",
"block.nukacraft.red_steel_stairs": "红钢楼梯",
"block.nukacraft.white_steel": "白钢",
"block.nukacraft.white_steel_column": "白钢柱",
"block.nukacraft.white_steel_corrugated_plate": "白钢瓦楞板",
"block.nukacraft.white_steel_slab": "白钢台阶",
"block.nukacraft.white_steel_stairs": "白钢楼梯",
"block.nukacraft.yellow_steel": "黄钢",
"block.nukacraft.yellow_steel_column": "黄钢柱",
"block.nukacraft.yellow_steel_corrugated_plate": "黄钢瓦楞板",
"block.nukacraft.yellow_steel_fence": "黄钢栅栏",
"block.nukacraft.yellow_steel_slab": "黄钢台阶",
"block.nukacraft.yellow_steel_stairs": "黄钢楼梯",
"block.nukacraft.rustedgreen_steel": "锈蚀绿钢",
"block.nukacraft.rustedred_steel": "锈蚀红钢",
"block.nukacraft.rusty_black_steel": "锈蚀黑钢",
"block.nukacraft.rusty_black_steel_corrugated_plate": "锈蚀黑钢瓦楞板",
"block.nukacraft.rusty_black_steel_slab": "锈蚀黑钢台阶",
"block.nukacraft.rusty_black_steel_stairs": "锈蚀黑钢楼梯",
"block.nukacraft.rusty_blue_steel": "锈蚀蓝钢",
"block.nukacraft.rusty_blue_steel_corrugated_plate": "锈蚀蓝钢瓦楞板",
"block.nukacraft.rusty_blue_steel_slab": "锈蚀蓝钢台阶",
"block.nukacraft.rusty_blue_steel_stairs": "锈蚀蓝钢楼梯",
"block.nukacraft.rusty_brown_steel": "锈蚀棕钢",
"block.nukacraft.rusty_brown_steel_corrugated_plate": "锈蚀棕钢瓦楞板",
"block.nukacraft.rusty_brown_steel_slab": "锈蚀棕钢台阶",
"block.nukacraft.rusty_brown_steel_stairs": "锈蚀棕钢楼梯",
"block.nukacraft.rusty_cyan_steel": "锈蚀青钢",
"block.nukacraft.rusty_cyan_steel_corrugated_plate": "锈蚀青钢瓦楞板",
"block.nukacraft.rusty_cyan_steel_slab": "锈蚀青钢台阶",
"block.nukacraft.rusty_cyan_steel_stairs": "锈蚀青钢楼梯",
"block.nukacraft.rusty_gray_steel": "锈蚀灰钢",
"block.nukacraft.rusty_gray_steel_corrugated_plate": "锈蚀灰钢瓦楞板",
"block.nukacraft.rusty_gray_steel_slab": "锈蚀灰钢台阶",
"block.nukacraft.rusty_gray_steel_stairs": "锈蚀灰钢楼梯",
"block.nukacraft.rusty_green_steel": "锈蚀绿钢",
"block.nukacraft.rusty_green_steel_corrugated_plate": "锈蚀绿钢瓦楞板",
"block.nukacraft.rusty_green_steel_slab": "锈蚀绿钢台阶",
"block.nukacraft.rusty_green_steel_stairs": "锈蚀绿钢楼梯",
"block.nukacraft.rusty_light_blue_steel": "锈蚀淡蓝钢",
"block.nukacraft.rusty_light_blue_steel_corrugated_plate": "锈蚀淡蓝钢瓦楞板",
"block.nukacraft.rusty_light_blue_steel_slab": "锈蚀淡蓝钢台阶",
"block.nukacraft.rusty_light_blue_steel_stairs": "锈蚀淡蓝钢楼梯",
"block.nukacraft.rusty_light_gray_steel": "锈蚀淡灰钢",
"block.nukacraft.rusty_light_gray_steel_corrugated_plate": "锈蚀淡灰钢瓦楞板",
"block.nukacraft.rusty_light_gray_steel_slab": "锈蚀淡灰钢台阶",
"block.nukacraft.rusty_light_gray_steel_stairs": "锈蚀淡灰钢楼梯",
"block.nukacraft.rusty_lime_steel": "锈蚀黄绿钢",
"block.nukacraft.rusty_lime_steel_corrugated_plate": "锈蚀黄绿钢瓦楞板",
"block.nukacraft.rusty_lime_steel_slab": "锈蚀黄绿钢台阶",
"block.nukacraft.rusty_lime_steel_stairs": "锈蚀黄绿钢楼梯",
"block.nukacraft.rusty_magenta_steel": "锈蚀品红钢",
"block.nukacraft.rusty_magenta_steel_corrugated_plate": "锈蚀品红钢瓦楞板",
"block.nukacraft.rusty_magenta_steel_slab": "锈蚀品红钢台阶",
"block.nukacraft.rusty_magenta_steel_stairs": "锈蚀品红钢楼梯",
"block.nukacraft.rusty_orange_steel": "锈蚀橙钢",
"block.nukacraft.rusty_orange_steel_corrugated_plate": "锈蚀橙钢瓦楞板",
"block.nukacraft.rusty_orange_steel_slab": "锈蚀橙钢台阶",
"block.nukacraft.rusty_orange_steel_stairs": "锈蚀橙钢楼梯",
"block.nukacraft.rusty_pink_steel": "锈蚀粉钢",
"block.nukacraft.rusty_pink_steel_corrugated_plate": "锈蚀粉钢瓦楞板",
"block.nukacraft.rusty_pink_steel_slab": "锈蚀粉钢台阶",
"block.nukacraft.rusty_pink_steel_stairs": "锈蚀粉钢楼梯",
"block.nukacraft.rusty_purple_steel": "锈蚀紫钢",
"block.nukacraft.rusty_purple_steel_corrugated_plate": "锈蚀紫钢瓦楞板",
"block.nukacraft.rusty_purple_steel_slab": "锈蚀紫钢台阶",
"block.nukacraft.rusty_purple_steel_stairs": "锈蚀紫钢楼梯",
"block.nukacraft.rusty_red_steel": "锈蚀红钢",
"block.nukacraft.rusty_red_steel_corrugated_plate": "锈蚀红钢瓦楞板",
"block.nukacraft.rusty_red_steel_slab": "锈蚀红钢台阶",
"block.nukacraft.rusty_red_steel_stairs": "锈蚀红钢楼梯",
"block.nukacraft.rusty_white_steel": "锈蚀白钢",
"block.nukacraft.rusty_white_steel_corrugated_plate": "锈蚀白钢瓦楞板",
"block.nukacraft.rusty_white_steel_slab": "锈蚀白钢台阶",
"block.nukacraft.rusty_white_steel_stairs": "锈蚀白钢楼梯",
"block.nukacraft.rusty_yellow_steel": "锈蚀黄钢",
"block.nukacraft.rusty_yellow_steel_corrugated_plate": "锈蚀黄钢瓦楞板",
"block.nukacraft.rusty_yellow_steel_slab": "锈蚀黄钢台阶",
"block.nukacraft.rusty_yellow_steel_stairs": "锈蚀黄钢楼梯",

# ===== tiles =====
"block.nukacraft.bluetile": "蓝色瓷砖",
"block.nukacraft.btile": "黑色瓷砖",
"block.nukacraft.brown_tile": "棕色瓷砖",
"block.nukacraft.cyantile": "青色瓷砖",
"block.nukacraft.darkgray_tile": "深灰色瓷砖",
"block.nukacraft.greentile": "绿色瓷砖",
"block.nukacraft.ligthblue_tile": "淡蓝色瓷砖",
"block.nukacraft.lime_tile": "黄绿色瓷砖",
"block.nukacraft.magtile": "品红色瓷砖",
"block.nukacraft.orange_tile": "橙色瓷砖",
"block.nukacraft.pink_tile": "粉红色瓷砖",
"block.nukacraft.prpltile": "紫色瓷砖",
"block.nukacraft.redtile": "红色瓷砖",
"block.nukacraft.white_tile": "白色瓷砖",
"block.nukacraft.yellow_tile": "黄色瓷砖",
"block.nukacraft.vttile": "避难所科技瓷砖",
"block.nukacraft.slitile": "切片瓷砖",

# ===== ores & minerals =====
"block.nukacraft.aluminium_block": "铝块",
"block.nukacraft.aluminium_ore": "铝矿石",
"block.nukacraft.deepslate_aluminium_ore": "深层铝矿石",
"block.nukacraft.black_titan_block": "黑钛块",
"block.nukacraft.black_titan_ore": "黑钛矿石",
"block.nukacraft.deepslate_black_titan_ore": "深层黑钛矿石",
"block.nukacraft.copper_block": "铜块",
"block.nukacraft.copper_ore": "铜矿石",
"block.nukacraft.lead_block": "铅块",
"block.nukacraft.lead_ore": "铅矿石",
"block.nukacraft.deepslate_lead_ore": "深层铅矿石",
"block.nukacraft.lead_sand": "含铅沙",
"block.nukacraft.lead_sandstone": "铅砂岩",
"block.nukacraft.quarts_ore": "石英矿石",
"block.nukacraft.deepslate_quarts_ore": "深层石英矿石",
"block.nukacraft.silver_block": "银块",
"block.nukacraft.silver_ore": "银矿石",
"block.nukacraft.deepslate_silver_ore": "深层银矿石",
"block.nukacraft.uranium_block": "铀块",
"block.nukacraft.uranium_ore": "铀矿石",
"block.nukacraft.deepslate_uranium_ore": "深层铀矿石",
"block.nukacraft.saturnite_block": "萨特尼矿块",
"block.nukacraft.saturnite_ore": "萨特尼矿石",
"block.nukacraft.deepslate_saturnite": "深层萨特尼矿石",
"block.nukacraft.ultracite_block": "辐射极琉矿块",
"block.nukacraft.ultracite_ore": "辐射极琉矿矿石",
"block.nukacraft.deepslate_ultracite_ore": "深层辐射极琉矿矿石",
"block.nukacraft.ultracite_magma": "辐射极琉矿岩浆块",
"block.nukacraft.ultracite_tuff": "辐射极琉矿凝灰岩",
"block.nukacraft.ultracite_tuff_ore": "辐射极琉矿凝灰岩矿石",
"block.nukacraft.pointed_ultracite_crystall": "辐射极琉矿晶簇",

# ===== common blocks =====
"block.nukacraft.acid_dirt": "酸性泥土",
"block.nukacraft.armedglass": "加固玻璃板",
"block.nukacraft.army_theatre_chair": "军剧院座椅",
"block.nukacraft.ash_smoker": "灰烬喷气口",
"block.nukacraft.ash_stone": "灰烬石",
"block.nukacraft.ashdirt": "灰烬泥土",
"block.nukacraft.ashgrass": "灰烬草",
"block.nukacraft.ashrose": "灰烬玫瑰",
"block.nukacraft.asphalt": "沥青",
"block.nukacraft.cracked_asphalt": "开裂沥青",
"block.nukacraft.barnplanks": "谷仓木板",
"block.nukacraft.wbarnplanks": "白色谷仓木板",
"block.nukacraft.bath_table": "浴桌",
"block.nukacraft.bblight": "亮光病叶",
"block.nukacraft.black_blood_leaf": "黑色血红叶丛",
"block.nukacraft.blood_leaf": "血红叶丛",
"block.nukacraft.gbloodleaf": "伽玛叶丛",
"block.nukacraft.qbloodleaf": "量子叶丛",
"block.nukacraft.blastcap": "爆裂帽菇",
"block.nukacraft.bogpad_item": "沼泽垃圾",
"block.nukacraft.boomblossom": "易燃热花朵",
"block.nukacraft.brocflower": "西兰花",
"block.nukacraft.brainfungus": "大脑真菌",
"block.nukacraft.gutshroom": "肠道蘑菇",
"block.nukacraft.hatter": "帽客蘑菇",
"block.nukacraft.megamorph_hatter": "超大帽客蘑菇",
"block.nukacraft.mutshootfungus": "发光变异蘑菇",
"block.nukacraft.mindfungus": "明心蘑菇",
"block.nukacraft.cage_block": "笼子方块",
"block.nukacraft.cage_plate": "笼板",
"block.nukacraft.cage_trapdoor": "笼活板门",
"block.nukacraft.rusttiresblock": "锈笼方块",
"block.nukacraft.rusty_cage_block": "锈笼方块",
"block.nukacraft.rusty_cage_door": "锈笼门",
"block.nukacraft.rusty_cage_plate": "锈笼板",
"block.nukacraft.rusty_cage_trapdoor": "锈笼活板门",
"block.nukacraft.comblock": "计算方块",
"block.nukacraft.cooler": "冷柜方块",
"block.nukacraft.cooler_rust": "冷柜",
"block.nukacraft.corrugated_steel_plate": "钢瓦楞板",
"block.nukacraft.rusty_corrugated_steel_plate": "锈蚀钢瓦楞板",
"block.nukacraft.crackberrybush": "爆竹莓丛",
"block.nukacraft.crackedwhitebricks": "开裂白砖",
"block.nukacraft.crackedwhitebricks_slab": "开裂白砖台阶",
"block.nukacraft.crackedwhitebricks_stairs": "开裂白砖楼梯",
"block.nukacraft.moss_whitebricks": "苔痕白砖",
"block.nukacraft.moss_whitebricks_slab": "苔痕白砖台阶",
"block.nukacraft.moss_whitebricks_stairs": "苔痕白砖楼梯",
"block.nukacraft.whitebricks": "白砖",
"block.nukacraft.whitebricks_slab": "白砖台阶",
"block.nukacraft.whitebricks_stairs": "白砖楼梯",
"block.nukacraft.whitebrick": "白砖",
"block.nukacraft.cranberry_grass": "蔓越莓草",
"block.nukacraft.cranberrygrass": "蔓越莓幼苗",
"block.nukacraft.cranberry_hollow_log": "蔓越莓空心木",
"block.nukacraft.cranberry_leaves": "蔓越莓树叶",
"block.nukacraft.cranberryleaves": "蔓越莓树叶",
"block.nukacraft.cranberry_log": "蔓越莓原木",
"block.nukacraft.cranberry_planks": "蔓越莓木板",
"block.nukacraft.cranberry_planks_fence": "蔓越莓木栅栏",
"block.nukacraft.cranberry_planks_gate": "蔓越莓木栅栏门",
"block.nukacraft.cranberry_planks_pressure_plate": "蔓越莓木压力板",
"block.nukacraft.cranberry_planks_slab": "蔓越莓木台阶",
"block.nukacraft.cranberry_planks_stairs": "蔓越莓木楼梯",
"block.nukacraft.cranberry_wood": "蔓越莓木块",
"block.nukacraft.cranberrywood_block": "蔓越莓木块",
"block.nukacraft.cranberry_wood_door": "蔓越莓木门",
"block.nukacraft.cranberry_wood_trapdoor": "蔓越莓木活板门",
"block.nukacraft.stripped_cranberry_log": "去皮蔓越莓原木",
"block.nukacraft.stripped_cranberry_wood": "去皮蔓越莓木",
"block.nukacraft.crkbrick_i": "开裂砖块",
"block.nukacraft.crkbrick_pipe": "开裂管道砖",
"block.nukacraft.crkbrick_r": "开裂砖块",
"block.nukacraft.crkbrick_t": "开裂砖块",
"block.nukacraft.crkbrick_vent": "开裂通风砖",
"block.nukacraft.cryocapsule": "冷冻舱",
"block.nukacraft.cryocapsuleact": "空冷冻舱",
"block.nukacraft.opencryocapsule": "敞开冷冻舱",
"block.nukacraft.dangerfloor": "危险地板",
"block.nukacraft.darkfloor": "暗色地板",
"block.nukacraft.darkgrayfloor": "深灰色地板",
"block.nukacraft.shelterfloor": "庇护所地板",
"block.nukacraft.dead_coralleaf": "凋零珊瑚叶",
"block.nukacraft.dead_daturan": "凋零曼陀罗丛",
"block.nukacraft.dead_decay_coral_fan": "凋零的败珊瑚扇",
"block.nukacraft.decay_coral_fan": "败珊瑚扇",
"block.nukacraft.coral_leaf": "珊瑚树叶",
"block.nukacraft.dead_punga": "凋零 Punega 丛",
"block.nukacraft.deadwood_block": "灰木块",
"block.nukacraft.deadwood_door": "灰木门",
"block.nukacraft.deadwood_hollow_log": "灰木空心木",
"block.nukacraft.deadwood_log": "灰木",
"block.nukacraft.dwoodlog_block": "灰木块",
"block.nukacraft.deadwood_planks": "灰木木板",
"block.nukacraft.deadwood_planks_fence": "枯木栅栏",
"block.nukacraft.deadwood_planks_gate": "枯木栅栏门",
"block.nukacraft.deadwood_planks_pressure_plate": "枯木压力板",
"block.nukacraft.deadwood_planks_slab": "灰木台阶",
"block.nukacraft.deadwood_planks_stairs": "灰木楼梯",
"block.nukacraft.deadwood_trapdoor": "灰木活板门",
"block.nukacraft.stripped_deadwood_block": "去皮山茱萸木",
"block.nukacraft.stripped_deadwood_log": "去皮山茱萸原木",
"block.nukacraft.dogwood": "山茱萸",
"block.nukacraft.death_flower": "凋零花",
"block.nukacraft.death_plant": "凋零草",
"block.nukacraft.dewdrop": "垂叶芽",
"block.nukacraft.dewdrop_sapling": "垂叶蕨",
"block.nukacraft.dinnerchair": "餐椅",
"block.nukacraft.door_cage": "铅砂岩",
"block.nukacraft.door_green": "绿门",
"block.nukacraft.door_hardened": "加固门",
"block.nukacraft.door_red": "红门",
"block.nukacraft.door_store": "商店门",
"block.nukacraft.door_terminal": "门控面板",
"block.nukacraft.door_white": "白门",
"block.nukacraft.rusty_green_door": "绿色锈门",
"block.nukacraft.rusty_red_door": "锈门",
"block.nukacraft.expbarrel": "爆炸桶",
"block.nukacraft.barrel": "放射性桶",
"block.nukacraft.filler_barrier": "填充方块",
"block.nukacraft.half_barrier": "填充台阶",
"block.nukacraft.firemushroom": "火焰蘑菇",
"block.nukacraft.fragmine": "破片地雷",
"block.nukacraft.fridge": "冰箱方块",
"block.nukacraft.fridge_rust": "冰箱",
"block.nukacraft.modern_fridge": "现代冰箱",
"block.nukacraft.frosted_door": "霜木门",
"block.nukacraft.frosted_hollow_log": "霜木空心木",
"block.nukacraft.frosted_leaves": "霜冻树叶",
"block.nukacraft.frosted_log": "霜木",
"block.nukacraft.frosted_planks": "蔓越莓木板",
"block.nukacraft.frosted_planks_fence": "霜木栅栏",
"block.nukacraft.frosted_planks_gate": "霜木栅栏门",
"block.nukacraft.frosted_planks_pressure_plate": "霜木压力板",
"block.nukacraft.frosted_planks_slab": "霜木台阶",
"block.nukacraft.frosted_planks_stairs": "蔓越莓木楼梯",
"block.nukacraft.frosted_wood": "霜木块",
"block.nukacraft.frosted_wood_fence": "霜木栅栏",
"block.nukacraft.frosted_wood_trapdoor": "霜木活板门",
"block.nukacraft.frostedwood_block": "霜木块",
"block.nukacraft.stripped_frosted_block": "去皮霜木块",
"block.nukacraft.stripped_frosted_log": "去皮霜木",
"block.nukacraft.stripped_frostedwood": "去皮霜木",
"block.nukacraft.stripped_frostedwood_block": "去皮霜木块",
"block.nukacraft.zander": "霜木栅栏",
"block.nukacraft.garvellll": "§m砾石 §r§o§d普雷斯顿砾石",
"block.nukacraft.geardoor": "避难所科技大门",
"block.nukacraft.vault_blast_door": "避难所大门",
"block.nukacraft.glow_grass": "发光草",
"block.nukacraft.glow_ice": "发光冰",
"block.nukacraft.glow_seagrass": "发光海草",
"block.nukacraft.rainbow_seagrass": "彩虹海草",
"block.nukacraft.glowfungus": "发光真菌",
"block.nukacraft.glowingwood": "发光木",
"block.nukacraft.goldtoilet": "§6黄金马桶★",
"block.nukacraft.heap_grass": "熔渣草",
"block.nukacraft.hollyhock": "蜀葵",
"block.nukacraft.immortal_green_leaves": "不朽绿叶",
"block.nukacraft.ind_button": "开关按钮",
"block.nukacraft.invertflower": "倒置花",
"block.nukacraft.irrad_beetroots": "辐照甜菜种子",
"block.nukacraft.joshua_door": "约书亚木门",
"block.nukacraft.joshua_fence": "约书亚木栅栏",
"block.nukacraft.joshua_fence_gate": "约书亚木栅栏门",
"block.nukacraft.joshua_leaves": "约书亚树树叶",
"block.nukacraft.joshua_planks": "约书亚木板",
"block.nukacraft.joshua_planks_slab": "约书亚木台阶",
"block.nukacraft.joshua_planks_stairs": "约书亚木楼梯",
"block.nukacraft.joshua_pressure_plate": "约书亚木压力板",
"block.nukacraft.joshua_trapdoor": "约书亚木活板门",
"block.nukacraft.joshuatree_block": "约书亚树木块",
"block.nukacraft.joshuatree_log": "约书亚树木",
"block.nukacraft.stripped_joshuatree_block": "去皮约书亚树木块",
"block.nukacraft.stripped_joshuatree_log": "去皮约书亚树木",
"block.nukacraft.largelamp": "大型灯",
"block.nukacraft.smalllamp": "小型灯",
"block.nukacraft.redlight": "红灯",
"block.nukacraft.lamp": "电子矿灯",
"block.nukacraft.medic_storage": "急救箱",
"block.nukacraft.monorail": "单轨方块",
"block.nukacraft.muddy_strangler_roots": "泥泞绞杀藤根",
"block.nukacraft.nuc_stat_block": "核能发电机",
"block.nukacraft.nuc_stat_control": "核能发电机",
"block.nukacraft.nuclear_generator_core": "核能发电机",
"block.nukacraft.nukacola_machine": "核子可乐贩卖机",
"block.nukacraft.nukacola_vending": "核子可乐机",
"block.nukacraft.nukamelon": "兆吨西瓜",
"block.nukacraft.nukamelon_blossom": "兆吨瓜花",
"block.nukacraft.office_chair": "办公椅",
"block.nukacraft.poison_grass": "毒草",
"block.nukacraft.powerblock": "布线方块",
"block.nukacraft.red_rocket_panel": "红火箭饰板",
"block.nukacraft.rr_steel_column": "红火箭钢柱",
"block.nukacraft.rreddoor": "红火箭门",
"block.nukacraft.rust_pipe": "锈蚀管道",
"block.nukacraft.rusty_pipe": "锈蚀管道",
"block.nukacraft.rusty_bush": "锈色灌木",
"block.nukacraft.rusty_leaves": "锈色树叶",
"block.nukacraft.rusty_steel": "锈蚀钢架",
"block.nukacraft.rusty_steel_bars": "锈蚀钢栏杆",
"block.nukacraft.rusty_steel_corrugated_plate": "锈蚀钢瓦楞板",
"block.nukacraft.rusty_steel_slab": "锈蚀钢台阶",
"block.nukacraft.rusty_steel_stairs": "锈蚀钢楼梯",
"block.nukacraft.steel": "钢架",
"block.nukacraft.steel_bars": "钢栏杆",
"block.nukacraft.steel_block": "钢块",
"block.nukacraft.steel_corrugated_plate": "钢瓦楞板",
"block.nukacraft.steel_shelf": "钢架台",
"block.nukacraft.steel_slab": "钢台阶",
"block.nukacraft.steel_stairs": "钢楼梯",
"block.nukacraft.steelfence": "钢栅栏",
"block.nukacraft.steelfence2": "钢栅栏",
"block.nukacraft.rsteelfence": "钢栅栏",
"block.nukacraft.rsteelfence2": "钢栅栏",
"block.nukacraft.tsteelfence": "钢栅栏",
"block.nukacraft.tsteelfence2": "钢栅栏",
"block.nukacraft.xsteelfence": "钢栅栏",
"block.nukacraft.xsteelfence2": "钢栅栏",
"block.nukacraft.scorched_earth": "焦土",
"block.nukacraft.scrap_block": "废料块",
"block.nukacraft.scrap_box": "废料箱",
"block.nukacraft.scrapmetall": "实心废料块",
"block.nukacraft.sea_trash": "水中垃圾",
"block.nukacraft.shelter_bars": "避难所科技栏杆",
"block.nukacraft.shelter_drill": "庇护所钻机",
"block.nukacraft.shelter_lamp": "避难所科技灯",
"block.nukacraft.shower_tap": "淋浴喷头",
"block.nukacraft.smooth_brick": "平滑砖",
"block.nukacraft.smooth_brick_slab": "平滑砖台阶",
"block.nukacraft.smooth_brick_stairs": "平滑砖楼梯",
"block.nukacraft.sootflower": "烟灰花",
"block.nukacraft.stragler_flower": "绞杀藤花",
"block.nukacraft.stragler_leaves": "绞杀藤树叶",
"block.nukacraft.strange_grass": "奇异草",
"block.nukacraft.strangler_roots": "绞杀藤根",
"block.nukacraft.strangler_vine": "绞杀藤蔓",
"block.nukacraft.strangler_wood": "绞杀藤纤维",
"block.nukacraft.supporttop": "支撑横梁",
"block.nukacraft.supportwall": "支撑横梁",
"block.nukacraft.supportwalltop": "支撑横梁",
"block.nukacraft.rustsupporttop": "锈蚀支撑横梁",
"block.nukacraft.rustsupportwall": "锈蚀支撑横梁",
"block.nukacraft.rustsupportwalltop": "锈蚀支撑横梁",
"block.nukacraft.table1": "监管人桌",
"block.nukacraft.table2": "监管人桌",
"block.nukacraft.table3": "监管人桌",
"block.nukacraft.table_lamp": "台灯",
"block.nukacraft.tablevt": "避难所科技桌",
"block.nukacraft.tech_chair": "座椅",
"block.nukacraft.techtable": "技术桌",
"block.nukacraft.tesla_block": "特斯拉柱",
"block.nukacraft.tesla_column": "特斯拉柱",
"block.nukacraft.toilet": "马桶",
"block.nukacraft.toxicfern": "毒蕨",
"block.nukacraft.vaultgen_block1": "避难所发电机方块",
"block.nukacraft.vaultgen_block2": "避难所发电机方块",
"block.nukacraft.vaultpillar": "避难所支柱",
"block.nukacraft.vent1": "通风口",
"block.nukacraft.vent2": "通风口",
"block.nukacraft.vent3": "通风口",
"block.nukacraft.vent_tube": "通风管",
"block.nukacraft.vtarmor": "避难所科技混凝土",
"block.nukacraft.vtcrate1": "避难所科技箱",
"block.nukacraft.vtcrate2": "监管人箱",
"block.nukacraft.vtdinner_chair": "避难所科技餐椅",
"block.nukacraft.vtlattice": "格架",
"block.nukacraft.vtprop": "钢支撑",
"block.nukacraft.vtprop2": "钢支撑",
"block.nukacraft.washbasin": "洗手盆",
"block.nukacraft.wasteland_terminal": "技术终端",
"block.nukacraft.basic_terminal": "终端机",
"block.nukacraft.radioterminal": "通讯终端",
"block.nukacraft.weapon_display": "武器展示架",
"block.nukacraft.workbench": "组装工作台",
"block.nukacraft.writtingdesk1": "写字桌",
"block.nukacraft.writtingdesk2": "写字桌",
"block.nukacraft.writtingdesk3": "写字桌",
"block.nukacraft.yucca": "丝兰",
"block.nukacraft.thistle": "蓟草",
"block.nukacraft.rad_rose": "辐射玫瑰",
"block.nukacraft.radaster": "炽红紫菀",
"block.nukacraft.aster": "紫菀",
"block.nukacraft.marygold": "万寿菊",
"block.nukacraft.pa_station_block": "动力装甲工作台",

# ===== items: materials =====
"item.nukacraft.acid_bucket": "酸液桶",
"item.nukacraft.poisonous_water_bucket": "毒水桶",
"item.nukacraft.dirty_water_bucket": "污水桶",
"item.nukacraft.bucket": "颜料桶",
"item.nukacraft.bucket_cyan": "青色颜料",
"item.nukacraft.bucket_green": "绿色颜料",
"item.nukacraft.bucket_light_gray": "淡灰色颜料",
"item.nukacraft.bucket_lime": "黄绿色颜料",
"item.nukacraft.bucket_magenta": "品红色颜料",
"item.nukacraft.bucket_purple": "紫色颜料",
"item.nukacraft.advmag": "进阶磁铁",
"item.nukacraft.magnet": "磁铁",
"item.nukacraft.agave_fruit": "龙舌兰果",
"item.nukacraft.agave_seed": "龙舌兰树苗",
"item.nukacraft.neoagave_fruit": "新龙舌兰果",
"item.nukacraft.neon_agave_seed": "霓虹龙舌兰树苗",
"item.nukacraft.retrogave_fruit": "§6复古波龙舌兰",
"item.nukacraft.aimproccesor": "瞄准卡",
"item.nukacraft.aiprocc": "基础电路板",
"item.nukacraft.adncan": "电路板",
"item.nukacraft.alumicond": "铝散热器",
"item.nukacraft.coppercond": "铜散热器",
"item.nukacraft.aluminium_ingot": "铝锭",
"item.nukacraft.aluminium_nugget": "铝粒",
"item.nukacraft.raw_aluminium": "未处理铝",
"item.nukacraft.army_circuit": "军用级电路",
"item.nukacraft.army_silencer": "军用消音器",
"item.nukacraft.ashdust": "灰烬粉尘",
"item.nukacraft.ash_tea": "灰烬玫瑰茶",
"item.nukacraft.aster_tea": "紫菀茶",
"item.nukacraft.sweet_aster_tea": "甜紫菀茶",
"item.nukacraft.sweet_ash_tea": "甜灰烬玫瑰茶",
"item.nukacraft.soot_tea": "烟灰茶",
"item.nukacraft.thistle_tea": "蓟草茶",
"item.nukacraft.atom": "§6原子审判",
"item.nukacraft.auto_aim_module": "火箭筒：自动瞄准模块",
"item.nukacraft.barrel_extender_missile": "火箭筒：延长的枪管",
"item.nukacraft.muzzle_blade_missile": "火箭筒：枪管刺刃",
"item.nukacraft.missile_drum": "火箭筒：导弹转轮",
"item.nukacraft.missile_magazine": "火箭筒：导弹弹匣",
"item.nukacraft.missile_mini": "小型导弹",
"item.nukacraft.banana_yucca_fruit": "香蕉丝兰果",
"item.nukacraft.bat_axe": "棒球斧",
"item.nukacraft.beerempty": "空啤酒瓶",
"item.nukacraft.black_titanium_ingot": "黑钛锭",
"item.nukacraft.black_titan_nugget": "黑钛粒",
"item.nukacraft.black_titanium_nugget": "黑钛粒",
"item.nukacraft.blackflux": "黑色通量",
"item.nukacraft.cobaltflux": "钴通量",
"item.nukacraft.undcobaltflux": "未处理钴通量",
"item.nukacraft.cleancobaltflux": "纯净钴通量",
"item.nukacraft.fluorflux": "荧光通量",
"item.nukacraft.undfluorflux": "未处理荧光通量",
"item.nukacraft.cleanfluorflux": "纯净荧光通量",
"item.nukacraft.scarletflux": "猩红通量",
"item.nukacraft.undscarletflux": "未处理猩红通量",
"item.nukacraft.cleanscarletflux": "纯净猩红通量",
"item.nukacraft.violetflux": "紫色通量",
"item.nukacraft.undvioletflux": "未处理紫色通量",
"item.nukacraft.cleanvioletflux": "纯净紫色通量",
"item.nukacraft.uraniumflux": "§a铀通量",
"item.nukacraft.cleanuraniumflux": "§a纯净铀通量",
"item.nukacraft.blamco": "咣当牌通心粉奶酪",
"item.nukacraft.bombberry": "爆浆莓",
"item.nukacraft.bomb_berry_seed": "§a爆浆莓树苗",
"item.nukacraft.bos_banner_pattern": "旗帜图案",
"item.nukacraft.bos_banner_pattern.desc": "钢铁兄弟会",
"item.nukacraft.boxer": "拳套护手",
"item.nukacraft.brahmin_fries": "双头牛薯条",
"item.nukacraft.bubble_apple": "苹果泡泡糖",
"item.nukacraft.cane": "手杖",
"item.nukacraft.cannonball": "加农炮弹",
"item.nukacraft.cerplate": "陶瓷板",
"item.nukacraft.cito_bat": "§6飞人球棒",
"item.nukacraft.classic10mm": "柯尔特 6520",
"item.nukacraft.classic10mm_zapaway": "经典 10mm 手枪",
"item.nukacraft.classic_laser_pistol": "经典激光手枪",
"item.nukacraft.copper": "铜锭",
"item.nukacraft.copperwires": "铜线",
"item.nukacraft.composite": "复合材料",
"item.nukacraft.crusher": "碎石机",
"item.nukacraft.daturan_root": "曼陀罗根",
"item.nukacraft.daturan_sprouts": "§3曼陀罗苗",
"item.nukacraft.dcleather": "死亡爪皮革",
"item.nukacraft.dewdrop_tear": "垂叶珠",
"item.nukacraft.dynamite_stick": "炸药棒",
"item.nukacraft.electronum": "电子矿",
"item.nukacraft.electrite_ingot": "电子矿锭",
"item.nukacraft.electrite_divider": "电子矿切割器",
"item.nukacraft.electrite_shell": "电子矿弹壳",
"item.nukacraft.electrite_lamp": "电子矿灯",
"item.nukacraft.elite_repair_kit": "超级修理包",
"item.nukacraft.repair_kit": "修理包",
"item.nukacraft.emcp": "空杯子",
"item.nukacraft.empty_cola": "空可乐瓶",
"item.nukacraft.excavator_torso": "§b挖掘者躯干",
"item.nukacraft.firemushpuree": "火焰蘑菇泥",
"item.nukacraft.firemushsoup": "火焰蘑菇汤",
"item.nukacraft.fusion_fruit": "聚变果",
"item.nukacraft.fusionfruit_seed": "§a聚变果树苗",
"item.nukacraft.giga_wheat_seeds": "巨粒小麦种子",
"item.nukacraft.gold_cranberry": "金色蔓越莓",
"item.nukacraft.gold_cranberry_seed": "§a金色蔓越莓树苗",
"item.nukacraft.golfdriver": "高尔夫球杆",
"item.nukacraft.goo": "黏浆",
"item.nukacraft.grenade_mirv": "破片手榴弹 MIRV",
"item.nukacraft.gunner_scope": "枪手瞄准镜",
"item.nukacraft.holy_grenade": "神圣手榴弹",
"item.nukacraft.hunting_scope": "狩猎瞄准镜",
"item.nukacraft.inda_abraxo_cleaner": "工业 Abraxo 清洁剂",
"item.nukacraft.irradiated_beetroot": "辐照甜菜",
"item.nukacraft.irradiated_beetroot_seed": "辐照甜菜种子",
"item.nukacraft.jethammer": "超级大锤",
"item.nukacraft.katana": "武士刀",
"item.nukacraft.lead_ingot": "铅锭",
"item.nukacraft.lead_nugget": "铅粒",
"item.nukacraft.leadplate": "铅板",
"item.nukacraft.gilded_lead": "镀金铅板",
"item.nukacraft.leatherhard": "硬化皮革",
"item.nukacraft.leg_weapon_parts": "§c特殊武器零件",
"item.nukacraft.unc_weapon_parts": "§a稀有武器零件",
"item.nukacraft.myth_weapon_parts": "§6非法武器零件",
"item.nukacraft.weapon_parts": "武器零件",
"item.nukacraft.loose_gears": "散落齿轮",
"item.nukacraft.loose_screws": "散落螺丝",
"item.nukacraft.loose_springs": "散落弹簧",
"item.nukacraft.machete": "开山刀",
"item.nukacraft.mantis_spawn_egg": "巨型螳螂刷怪蛋",
"item.nukacraft.megasloth": "巨懒蘑菇",
"item.nukacraft.merchant_spawn_egg": "废土商人刷怪蛋",
"item.nukacraft.mini_nuke": "§c迷你核弹",
"item.nukacraft.missile": "导弹",
"item.nukacraft.missile_launcher": "火箭筒",
"item.nukacraft.molded_plastic": "模压塑料",
"item.nukacraft.molotov": "汽油弹",
"item.nukacraft.molotov_cola": "可乐汽油弹",
"item.nukacraft.muggy_securitron_spawn_egg": "小黏人刷怪蛋",
"item.nukacraft.mutfruit": "变异果",
"item.nukacraft.muttfruit": "变异果",
"item.nukacraft.muttfruit_seed": "变异果树苗",
"item.nukacraft.molerat_leather": "鼹鼠皮革",
"item.nukacraft.molerat_teeth": "鼹鼠牙",
"item.nukacraft.mirelurk_egg": "泥沼蟹蛋",
"item.nukacraft.mirelurk_eggshell": "泥沼蟹蛋壳",
"item.nukacraft.claw_milelurk": "泥沼蟹爪",
"item.nukacraft.razor_milelurk": "泥沼蟹剃刀",
"item.nukacraft.neutron_rod": "中子棒",
"item.nukacraft.neutron_rod_seed": "§a中子棒种子",
"item.nukacraft.nuc_holder": "核支柱",
"item.nukacraft.nuclear_waste": "核废料",
"item.nukacraft.nuka_cola": "核子可乐",
"item.nukacraft.nuka_cola_ice": "§b冰镇核子可乐",
"item.nukacraft.nuka_frutti": "核子莓果可乐",
"item.nukacraft.nuka_frutti_ice": "§b冰镇核子莓果可乐",
"item.nukacraft.nukabreak": "§c核子小憩",
"item.nukacraft.nukamelon_piece": "兆吨西瓜片",
"item.nukacraft.nukamelon_seed": "兆吨西瓜种子",
"item.nukacraft.nukaroot": "核子根",
"item.nukacraft.nukaroot_seed": "核子根种子",
"item.nukacraft.old_scope": "老式瞄准镜",
"item.nukacraft.old_silencer": "老式消音器",
"item.nukacraft.piezonucleic_divider": "§6压核切割器",
"item.nukacraft.pmt1": "黏稠物",
"item.nukacraft.poolcue": "台球杆",
"item.nukacraft.powdergun": "黑火药步枪",
"item.nukacraft.power_armor_frame": "§3动力装甲骨架",
"item.nukacraft.prewarmoney": "战前纸币",
"item.nukacraft.prism_leaf": "棱彩树叶",
"item.nukacraft.punga_fruit": "蒲加果",
"item.nukacraft.punga_seed": "蒲加种子",
"item.nukacraft.pures": "即时土豆泥",
"item.nukacraft.purple_reagent": "紫色试剂",
"item.nukacraft.quantumleaf": "量子叶",
"item.nukacraft.quantumleaf_": "量子叶丛",
"item.nukacraft.quartz_divider": "§a石英切割器",
"item.nukacraft.quartz_piece": "石英碎块",
"item.nukacraft.quartz_plate": "石英板",
"item.nukacraft.quartz_shell": "石英弹壳",
"item.nukacraft.radaway": "消辐宁",
"item.nukacraft.radx": "抗辐宁",
"item.nukacraft.razorblade": "剃刀片",
"item.nukacraft.reducer": "减震器",
"item.nukacraft.reducts": "减震器",
"item.nukacraft.resin_glow": "发光树脂",
"item.nukacraft.raw_adhesive": "生黏胶",
"item.nukacraft.raw_bloatfly": "生巨大苍蝇肉",
"item.nukacraft.raw_brahmin_meat": "生双头牛肉",
"item.nukacraft.raw_deadclaw_meat": "生死亡爪肉",
"item.nukacraft.raw_iguana_meat": "生鬣蜥肉",
"item.nukacraft.raw_mirelurk_meat": "生泥沼蟹肉",
"item.nukacraft.raw_molerat": "生鼹鼠肉",
"item.nukacraft.raw_radroach_meat": "生辐射蟑螂肉",
"item.nukacraft.raw_saturnite": "未处理萨特尼矿",
"item.nukacraft.raw_steel": "未处理钢",
"item.nukacraft.raw_uranium": "未处理铀",
"item.nukacraft.raw_cloth": "生布料",
"item.nukacraft.raw_fertilizer": "生肥料",
"item.nukacraft.raw_lead": "未处理铅",
"item.nukacraft.raw_rubber": "橡胶",
"item.nukacraft.raw_silver": "未处理银",
"item.nukacraft.cooked_bloatfly": "熟巨大苍蝇肉",
"item.nukacraft.cooked_brahmin_meat": "熟双头牛肉",
"item.nukacraft.cooked_deadclaw_meat": "熟死亡爪肉",
"item.nukacraft.cooked_iguana_meat": "熟鬣蜥肉",
"item.nukacraft.cooked_mirelurk_meat": "熟泥沼蟹肉",
"item.nukacraft.cooked_molerat": "熟鼹鼠肉",
"item.nukacraft.cooked_radroach_meat": "熟辐射蟑螂肉",
"item.nukacraft.silicate": "硅酸盐粉末",
"item.nukacraft.silver_ingot": "银锭",
"item.nukacraft.silver_nugget": "银粒",
"item.nukacraft.steel_ingot": "钢锭",
"item.nukacraft.steel_nugget": "钢粒",
"item.nukacraft.steelbowl": "钢碗",
"item.nukacraft.silt_bean": "淤泥豆",
"item.nukacraft.silt_bean_seed": "淤泥豆种子",
"item.nukacraft.silt_puree": "淤泥豆浓汤",
"item.nukacraft.silt_soup": "淤泥豆汤",
"item.nukacraft.spoiled_tato": "腐坏土豆",
"item.nukacraft.wild_tato": "土豆",
"item.nukacraft.tato_salad": "土豆沙拉",
"item.nukacraft.vegetable_soup": "蔬菜汤",
"item.nukacraft.special_soup": "§aS.P.E.C.I.A.L. 浓汤",
"item.nukacraft.starberry": "星光莓",
"item.nukacraft.starlight_seed": "星光树苗",
"item.nukacraft.stealth_boy": "隐形小子",
"item.nukacraft.steel_ball": "滑膛枪弹丸",
"item.nukacraft.steel_balls": ".50 弹丸",
"item.nukacraft.stimpak": "治疗针",
"item.nukacraft.super_stimpak": "超级治疗针",
"item.nukacraft.spices": "香料",
"item.nukacraft.saturnite_ingot": "萨特尼矿锭",
"item.nukacraft.saturnite_nugget": "萨特尼矿粒",
"item.nukacraft.shiv": "削尖锥",
"item.nukacraft.shotshell": "霰弹",
"item.nukacraft.shotgun": "霰弹枪",
"item.nukacraft.skill_book_agility": "§6技能书：敏捷",
"item.nukacraft.skill_book_charisma": "§6技能书：魅力",
"item.nukacraft.skill_book_endurance": "§6技能书：耐力",
"item.nukacraft.skill_book_intelligence": "§6技能书：智力",
"item.nukacraft.skill_book_luck": "§6技能书：运气",
"item.nukacraft.skill_book_perception": "§6技能书：感知",
"item.nukacraft.skill_book_strength": "§6技能书：力量",
"item.nukacraft.not_so_special_book": "§c你很不SPECIAL！手册",
"item.nukacraft.youre_special_book": "§9你很SPECIAL！手册",
"item.nukacraft.testicules_brahmin": "双头牛睾丸",
"item.nukacraft.tire_axe": "轮胎斧",
"item.nukacraft.ultracite": "辐射极琉矿",
"item.nukacraft.ultrbar": "辐射极琉矿稳定器",
"item.nukacraft.ultracite_divider": "§c辐射极琉矿切割器",
"item.nukacraft.ultracite_shell": "§a辐射极琉矿弹壳",
"item.nukacraft.ultraviolet_carrot": "紫外胡萝卜",
"item.nukacraft.uf_carrot_seed": "紫外胡萝卜种子",
"item.nukacraft.uranium_ingot": "铀锭",
"item.nukacraft.uranium_nugget": "铀粒",
"item.nukacraft.uranrod": "铀棒",
"item.nukacraft.uranium_rod": "铀棒",
"item.nukacraft.watercola": "水味可乐瓶",
"item.nukacraft.whitebrick": "白砖",
"item.nukacraft.wrench": "扳手",
"item.nukacraft.xander_root": "山萝卜根",
"item.nukacraft.nbloodleafi": "血红叶",
"item.nukacraft.blood_leaf_bush": "血红叶丛",
"item.nukacraft.gamma_leaf": "伽玛叶",
"item.nukacraft.gamma_leaf_bush": "伽玛叶丛",
"item.nukacraft.crackberry_seed": "爆竹莓树苗",
"item.nukacraft.cranberry_seed": "蔓越莓树苗",
"item.nukacraft.ginseng_seed": "人参根种子",
"item.nukacraft.fertilizer": "肥料",
"item.nukacraft.toilet_paper": "卫生纸",
"item.nukacraft.scrap": "废料金属",
"item.nukacraft.holotape_cyan": "彩色全息磁带",
"item.nukacraft.holotape_gold": "彩色全息磁带",
"item.nukacraft.holotape_green": "彩色全息磁带",
"item.nukacraft.holotape_orange": "彩色全息磁带",
"item.nukacraft.holotape_red": "彩色全息磁带",
"item.nukacraft.holotape_violet": "彩色全息磁带",
"item.nukacraft.holotape_white": "彩色全息磁带",
"item.nukacraft.pipboy": "哔哔小子",
"item.nukacraft.robot_boots": "机器人护腿",
"item.nukacraft.robot_chest": "机器人护胸",
"item.nukacraft.robot_helmet": "机器人头盔",
"item.nukacraft.robot_leggings": "机器人护胫",
"item.nukacraft.combat_boots": "战斗装甲军靴",
"item.nukacraft.combat_chest": "战斗装甲胸甲",
"item.nukacraft.combat_helmet": "战斗装甲头盔",
"item.nukacraft.combat_leggings": "战斗装甲护腿",
"item.nukacraft.gold_boots": "黄金军靴",
"item.nukacraft.gold_chest": "黄金护胸",
"item.nukacraft.gold_helmet": "黄金头盔",
"item.nukacraft.gold_leggings": "黄金护腿",
"item.nukacraft.iron_boots": "铁制军靴",
"item.nukacraft.iron_chest": "铁制护胸",
"item.nukacraft.iron_helmet": "铁制头盔",
"item.nukacraft.iron_leggings": "铁制护腿",
"item.nukacraft.leather_boots": "皮质军靴",
"item.nukacraft.leather_chest": "皮质护胸",
"item.nukacraft.leather_helmet": "皮质帽",
"item.nukacraft.leather_leggings": "皮质护腿",
"item.nukacraft.metal_boots": "金属军靴",
"item.nukacraft.metal_chest": "金属护胸",
"item.nukacraft.metal_helmet": "金属头盔",
"item.nukacraft.metal_leggings": "金属护腿",
"item.nukacraft.wooden_boots": "木制军靴",
"item.nukacraft.wooden_chest": "木制护胸",
"item.nukacraft.wooden_helmet": "木制头盔",
"item.nukacraft.wooden_leggings": "木制护腿",
"item.nukacraft.scout_boots": "侦察兵军靴",
"item.nukacraft.scout_chest": "侦察兵护胸",
"item.nukacraft.scout_helmet": "侦察兵面罩",
"item.nukacraft.scout_leggings": "侦察兵护腿",
"item.nukacraft.trapper_boots": "陷捕者军靴",
"item.nukacraft.trapper_chest": "陷捕者护胸",
"item.nukacraft.trapper_helmet": "陷捕者头盔",
"item.nukacraft.trapper_leggings": "陷捕者护腿",
"item.nukacraft.raider_helmet": "掠夺者头盔",
"item.nukacraft.raider_left_arm": "掠夺者左臂",
"item.nukacraft.raider_left_leg": "掠夺者左腿",
"item.nukacraft.raider_right_arm": "掠夺者右臂",
"item.nukacraft.raider_right_leg": "掠夺者右腿",
"item.nukacraft.raider_torso": "掠夺者躯干",
"item.nukacraft.raider_spawn_egg": "掠夺者刷怪蛋",
"item.nukacraft.raiders_boots": "掠夺者军靴",
"item.nukacraft.raiders_chest": "掠夺者护胸",
"item.nukacraft.raiders_helmet": "掠夺者兜帽",
"item.nukacraft.raiders_leggings": "掠夺者护腿",
"item.nukacraft.vault_dweller_boots": "避难所居民军靴",
"item.nukacraft.vault_dweller_chest": "避难所居民连体制服",
"item.nukacraft.vault_dweller_leggings": "避难所居民护腿",
"item.nukacraft.vault_science_chest": "避难所科学家长袍",
"item.nukacraft.vault_science_leggings": "避难所科学家护腿",
"item.nukacraft.vault_security_boots": "§c避难所保安军靴",
"item.nukacraft.vault_security_chest": "§c避难所保安护胸",
"item.nukacraft.vault_security_helmet": "§c避难所保安头盔",
"item.nukacraft.vault_security_leggings": "§c避难所保安护腿",
"item.nukacraft.ncr_pa_boots": "§6NCR 拾荒军靴",
"item.nukacraft.ncr_pa_chest": "§6NCR 拾荒护胸",
"item.nukacraft.ncr_pa_helmet": "§6NCR 拾荒头盔",
"item.nukacraft.ncr_pa_leggings": "§6NCR 拾荒护腿",
"item.nukacraft.ncrpa_helmet": "NCR 游骑兵头盔",
"item.nukacraft.ncrpa_left_arm": "NCR 游骑兵左臂甲",
"item.nukacraft.ncrpa_left_leg": "NCR 游骑兵左腿",
"item.nukacraft.ncrpa_right_arm": "NCR 游骑兵右臂甲",
"item.nukacraft.ncrpa_right_leg": "NCR 游骑兵右腿",
"item.nukacraft.ncrpa_torso": "NCR 游骑兵躯干",
"item.nukacraft.ranger_boots": "NCR 游骑兵军靴",
"item.nukacraft.ranger_chest": "NCR 游骑兵护胸",
"item.nukacraft.ranger_helmet": "NCR 游骑兵头盔",
"item.nukacraft.ranger_leggings": "NCR 游骑兵护腿",
"item.nukacraft.overboss_helmet": "大头目头盔",
"item.nukacraft.overboss_left_arm": "大头目左臂甲",
"item.nukacraft.overboss_left_leg": "大头目左腿",
"item.nukacraft.overboss_right_arm": "大头目右臂甲",
"item.nukacraft.overboss_right_leg": "大头目右腿",
"item.nukacraft.overboss_torso": "大头目躯干",
"item.nukacraft.t45_helmet": "T-45 头盔",
"item.nukacraft.t45_left_arm": "T-45 左臂甲",
"item.nukacraft.t45_left_leg": "T-45 左腿",
"item.nukacraft.t45_right_arm": "T-45 右臂甲",
"item.nukacraft.t45_right_leg": "T-45 右腿",
"item.nukacraft.t45_torso": "T-45 躯干",
"item.nukacraft.t51_helmet": "§bT-51 头盔",
"item.nukacraft.t51_left_arm": "§bT-51 左臂甲",
"item.nukacraft.t51_left_leg": "§bT-51 左腿",
"item.nukacraft.t51_right_arm": "§bT-51 右臂甲",
"item.nukacraft.t51_right_leg": "§bT-51 右腿",
"item.nukacraft.t51_torso": "§bT-51 躯干",
"item.nukacraft.t60_helmet": "§eT-60 头盔",
"item.nukacraft.t60_left_arm": "§eT-60 左臂甲",
"item.nukacraft.t60_left_leg": "§eT-60 左腿",
"item.nukacraft.t60_right_arm": "§eT-60 右臂甲",
"item.nukacraft.t60_right_leg": "§eT-60 右腿",
"item.nukacraft.t60_torso": "§eT-60 躯干",
"item.nukacraft.t65_helmet": "§cT65 头盔",
"item.nukacraft.t65_left_arm": "§cT65 左臂甲",
"item.nukacraft.t65_left_leg": "§cT65 左腿",
"item.nukacraft.t65_right_arm": "§cT65 右臂甲",
"item.nukacraft.t65_right_leg": "§cT65 右腿",
"item.nukacraft.t65_torso": "§cT65 躯干",
"item.nukacraft.x01_helmet": "§cX-01 头盔",
"item.nukacraft.x01_left_arm": "§cX-01 左臂甲",
"item.nukacraft.x01_left_leg": "§cX-01 左腿",
"item.nukacraft.x01_right_arm": "§cX-01 右臂甲",
"item.nukacraft.x01_right_leg": "§cX-01 右腿",
"item.nukacraft.x01_torso": "§cX-01 躯干",
"item.nukacraft.x02_helmet": "§cX-02 头盔",
"item.nukacraft.x02_left_arm": "§cX-02 左臂甲",
"item.nukacraft.x02_left_leg": "§cX-02 左腿",
"item.nukacraft.x02_right_arm": "§cX-02 右臂甲",
"item.nukacraft.x02_right_leg": "§cX-02 右腿",
"item.nukacraft.x02_torso": "§cX-02 躯干",
"item.nukacraft.x03_helmet": "§6X-03 头盔",
"item.nukacraft.x03_left_arm": "§6X-03 左臂甲",
"item.nukacraft.x03_left_leg": "§6X-03 左腿",
"item.nukacraft.x03_right_arm": "§6X-03 右臂甲",
"item.nukacraft.x03_right_leg": "§6X-03 右腿",
"item.nukacraft.x03_torso": "§6X-03 躯干",

# ===== 刷怪蛋 =====
"item.nukacraft.ant_spawn_egg": "巨型蚂蚁刷怪蛋",
"item.nukacraft.assaultron_spawn_egg": "突袭者刷怪蛋",
"item.nukacraft.berserk_securitron_spawn_egg": "狂暴安保机器人刷怪蛋",
"item.nukacraft.bighorner_spawn_egg": "大角羊刷怪蛋",
"item.nukacraft.bloatfly_spawn_egg": "巨大苍蝇刷怪蛋",
"item.nukacraft.brahmin_spawn_egg": "双头牛刷怪蛋",
"item.nukacraft.cazador_spawn_egg": "尾刺螫蝇刷怪蛋",
"item.nukacraft.companion_spawn_egg": "同伴刷怪蛋",
"item.nukacraft.deathclaw_spawn_egg": "死亡爪刷怪蛋",
"item.nukacraft.eyebot_spawn_egg": "眼球机刷怪蛋",
"item.nukacraft.frank_horrigan_spawn_egg": "弗兰克·霍里根刷怪蛋",
"item.nukacraft.ghoul_spawn_egg": "狂尸鬼刷怪蛋",
"item.nukacraft.iguana_spawn_egg": "鬣蜥刷怪蛋",
"item.nukacraft.mirelurk_spawn_egg": "泥沼蟹刷怪蛋",
"item.nukacraft.molerat_spawn_egg": "鼹鼠刷怪蛋",
"item.nukacraft.mothman_spawn_egg": "天蛾人刷怪蛋",
"item.nukacraft.protectron_spawn_egg": "保护者刷怪蛋",
"item.nukacraft.radroach_spawn_egg": "辐射蟑螂刷怪蛋",
"item.nukacraft.radscorpion_spawn_egg": "辐射蝎刷怪蛋",
"item.nukacraft.radstag_spawn_egg": "辐射鹿刷怪蛋",
"item.nukacraft.raider_spawn_egg": "掠夺者刷怪蛋",
"item.nukacraft.robobrain_spawn_egg": "机器脑刷怪蛋",
"item.nukacraft.robodog_spawn_egg": "机器狗刷怪蛋",
"item.nukacraft.securitron_spawn_egg": "安保机器人刷怪蛋",
"entity.nukacraft.companion_spawn_egg": "同伴刷怪蛋",
"entity.nukacraft.ant": "巨型蚂蚁",
"entity.nukacraft.assaultron": "突袭者",
"entity.nukacraft.bloatfly": "巨大苍蝇",
"entity.nukacraft.brahmin": "双头牛",
"entity.nukacraft.companion": "同伴",
"entity.nukacraft.deathclaw": "死亡爪",
"entity.nukacraft.eyebot": "眼球机",
"entity.nukacraft.ghoul": "狂尸鬼",
"entity.nukacraft.mirelurk": "泥沼蟹",
"entity.nukacraft.molerat": "鼹鼠",
"entity.nukacraft.mothman": "天蛾人",
"entity.nukacraft.mysterious_stranger": "神秘陌生人",
"entity.nukacraft.protectron": "保护者",
"entity.nukacraft.radroach": "辐射蟑螂",
"entity.nukacraft.radscorpion": "辐射蝎",
"entity.nukacraft.radstag": "辐射鹿",
"entity.nukacraft.raider": "掠夺者",
"entity.nukacraft.robobrain": "机器脑",
"entity.nukacraft.robodog": "机器狗",
"item.nukacraft.power_armor_frame_entity": "动力装甲骨架",

# ===== 弹药 =====
"item.nukacraft.round10mm": "10mm 子弹",
"item.nukacraft.round10mm_piercing": "10mm 穿甲弹",
"item.nukacraft.round127": "12.7mm 子弹",
"item.nukacraft.round127_piercing": "12.7mm 穿甲弹",
"item.nukacraft.round22": ".22LR 子弹",
"item.nukacraft.round22_piercing": ".22LR 穿甲弹",
"item.nukacraft.round308": ".308 子弹",
"item.nukacraft.round38": ".38 子弹",
"item.nukacraft.round38_piercing": ".38 穿甲弹",
"item.nukacraft.round380": ".380 子弹",
"item.nukacraft.round380_piercing": ".380 穿甲弹",
"item.nukacraft.round44": ".44 子弹",
"item.nukacraft.round44_piercing": ".44 穿甲弹",
"item.nukacraft.round45": ".45 子弹",
"item.nukacraft.round45_piercing": ".45 穿甲弹",
"item.nukacraft.round50": ".50 子弹",
"item.nukacraft.round50_piercing": ".50 穿甲弹",
"item.nukacraft.round556": "5.56 子弹",
"item.nukacraft.round556_piercing": "5.56 穿甲弹",
"item.nukacraft.round5mm": "5mm 子弹",
"item.nukacraft.round5mm_piercing": "5mm 穿甲弹",
"item.nukacraft.pistol10mm": "10mm 手枪",
"item.nukacraft.scout10mm": "侦察 10mm 手枪",

# ===== 枪械配件 =====
"item.nukacraft.laser_pistol": "激光手枪",
"item.nukacraft.laser_rifle": "激光步枪",
"item.nukacraft.laser_auto_barrel": "激光枪：自动枪管",
"item.nukacraft.laser_long_grip": "激光枪：长枪托",
"item.nukacraft.laser_long_scout_optics": "激光枪：远程侦察瞄准镜",
"item.nukacraft.laser_protectron_barrel": "激光枪：保护者机械手",
"item.nukacraft.laser_sniper_barrel": "激光枪：狙击枪管",
"item.nukacraft.laser_tactical_grip": "激光枪：战术枪托",
"item.nukacraft.laser_weighted_grip": "激光枪：配重枪托",
"item.nukacraft.laser_all_vision": "观测模块「全视野」",
"item.nukacraft.tesla_rifle": "特斯拉步枪",
"item.nukacraft.tesla_auto_barrel": "特斯拉步枪：自动枪管",
"item.nukacraft.tesla_charging_barrel": "特斯拉步枪：充能枪管",
"item.nukacraft.tesla_iron_sight": "特斯拉步枪：机瞄",
"item.nukacraft.tesla_overheat_barrel": "特斯拉步枪：过载枪管",
"item.nukacraft.tesla_rail_barrel": "特斯拉步枪：轨道枪管",
"item.nukacraft.tesla_tactical_grip": "特斯拉步枪：战术枪托",
"item.nukacraft.minigun": "§c旋转机枪",
"item.nukacraft.minigun_drum_mag": "旋转机枪：弹鼓",
"item.nukacraft.minigun_extend_mag": "旋转机枪：加长弹匣",
"item.nukacraft.minigun_long_barrel": "旋转机枪：长枪管",
"item.nukacraft.minigun_shredder": "旋转机枪：碎裂器",
"item.nukacraft.minigun_shredder_heat": "旋转机枪：过热碎裂器",
"item.nukacraft.minigun_shredder_saturnite": "旋转机枪：萨特尼碎裂器",
"item.nukacraft.minigun_six_barrel": "旋转机枪：六枪管",
"item.nukacraft.broadsider": "军舰炮",
"item.nukacraft.broadsider_barrel": "军舰炮：加长炮管",
"item.nukacraft.broadsider_magazine": "军舰炮：加长弹匣",
"item.nukacraft.flamer": "军用火焰喷射器",
"item.nukacraft.handmade_flamer": "手工火焰喷射器",
"item.nukacraft.flamer_compress_barrel": "火焰喷射器：压缩喷嘴",
"item.nukacraft.flamer_evaporative_barrel": "火焰喷射器：蒸发喷嘴",
"item.nukacraft.gatling_laser_correction_lens": "激光机枪：校正透镜",
"item.nukacraft.gatling_laser_eight_barrel": "激光机枪：八联枪管",
"item.nukacraft.gatling_laser_industrial_barrel": "激光机枪：工业枪管",
"item.nukacraft.pipepistol": "管子手枪",
"item.nukacraft.piperevolver": "管子左轮",
"item.nukacraft.pipe_carbine_grip": "管子枪：卡宾枪托",
"item.nukacraft.pipe_compensator": "管子枪：补偿器",
"item.nukacraft.pipe_flame_hider": "管子枪：消焰器",
"item.nukacraft.pipe_heavy_barrel": "管子枪：重型枪管",
"item.nukacraft.pipe_long_barrel": "管子枪：长枪管",
"item.nukacraft.pipe_long_grip": "管子枪：长枪托",
"item.nukacraft.pipe_pistol_grip": "管子枪：手枪握把",
"item.nukacraft.pipe_silencer": "管子枪：消音器",
"item.nukacraft.pipe_tactical_grip": "管子枪：战术握把",
"item.nukacraft.pipe_wrench": "管钳",
"item.nukacraft.pistol_collimator_sight": "准直瞄准镜",
"item.nukacraft.pistol_compensator": "手枪：补偿器",
"item.nukacraft.pistol_drum_magazine": "手枪：弹鼓",
"item.nukacraft.pistol_extended_magazine": "手枪：加长弹匣",
"item.nukacraft.pistol_flame_hider": "手枪：消焰器",
"item.nukacraft.pistol_heavy_barrel": "手枪：重型枪管",
"item.nukacraft.pistol_holographic_sight": "全息瞄准镜",
"item.nukacraft.pistol_huge_magazine": "手枪：超大弹匣",
"item.nukacraft.pistol_hunting_optics": "狩猎瞄准镜",
"item.nukacraft.pistol_iron_sight": "机瞄",
"item.nukacraft.pistol_long_barrel": "手枪：长枪管",
"item.nukacraft.pistol_quick_magazine": "手枪：快拆弹匣",
"item.nukacraft.pistol_scout_sight": "侦察瞄准镜",
"item.nukacraft.pistol_silencer": "手枪：消音器",
"item.nukacraft.pistol_specialised_grip": "手枪：专用握把",
"item.nukacraft.pistol_tactical_grip": "手枪：战术握把",
"item.nukacraft.pistol_weighted_grip": "手枪：配重握把",
"item.nukacraft.pump_long_barrel": "泵动霰弹枪：长枪管",
"item.nukacraft.pump_long_grip": "泵动霰弹枪：长枪托",
"item.nukacraft.pump_pistol_grip": "泵动霰弹枪：手枪握把",
"item.nukacraft.pump_shield_barrel": "泵动霰弹枪：枪管护盾",
"item.nukacraft.pump_silencer_barrel": "泵动霰弹枪：消音枪管",
"item.nukacraft.pump_tactical_grip": "泵动霰弹枪：战术枪托",
"item.nukacraft.pump_weighted_grip": "泵动霰弹枪：配重枪托",
"item.nukacraft.service_rifle": "制式步枪",
"item.nukacraft.handmade_spear": "手工长矛",
"item.nukacraft.handmade_scope": "手工瞄准镜",
"item.nukacraft.handmade_stock": "手工枪托",
"item.nukacraft.handmade_collimator": "手工准直瞄准镜",
"item.nukacraft.handmade_flashhider": "手工消焰器",
"item.nukacraft.handmade_flamer": "手工火焰喷射器",
"item.nukacraft.liberator": "解放者",
"item.nukacraft.komi": "赤色分子拍击棒",
"item.nukacraft.security_baton": "警棍",
"item.nukacraft.baseball_bat": "棒球棒",
"item.nukacraft.baseball_grenade": "棒球手榴弹",
"item.nukacraft.securitron_gun": "安保机枪",
"item.nukacraft.securitron_laser": "安保激光",
"item.nukacraft.assaultron_laser": "突袭者激光",
"item.nukacraft.scabbard": "近战配件：刀鞘",
"item.nukacraft.sharp_blade": "近战配件：锋利刀刃",
"item.nukacraft.wide_blade": "近战配件：宽刃",
"item.nukacraft.heavy_handle": "近战配件：重型握柄",
"item.nukacraft.stock_shield": "重武器：弹道护盾",
"item.nukacraft.stun_grenade": "震撼手榴弹",
"item.nukacraft.toxic_floater_grenade": "毒泡手榴弹",
"item.nukacraft.flame_floater_grenade": "火泡手榴弹",
"item.nukacraft.molotov_cola": "可乐汽油弹",
"item.nukacraft.baseball_grenade": "棒球手榴弹",
}
